Update of configure scripts.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -272,7 +272,7 @@ PACKAGE_BUGREPORT=
 
 ac_unique_file="README.draco"
 ac_subdirs_all="$ac_subdirs_all tools src autodoc"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MPI_INC MPI_LIB SPRNG_INC SPRNG_LIB PCG_LIB AZTEC_INC AZTEC_LIB GSL_INC GSL_LIB GSLCBLAS_INC GSLCBLAS_LIB TRILINOS_INC TRILINOS_LIB METIS_INC METIS_LIB LAPACK_LIB GANDOLF_LIB EOSPAC5_LIB GRACE_INC GRACE_LIB latex_yes_no doxygen_output_top PYTHON_PATH PERL_PATH CVS_PATH GHOSTVIEW LATEX LATEXFLAGS BIBTEX BIBTEXFLAGS XDVI XDVIFLAGS DVIPS DVIPSFLAGS LP LPFLAGS DOXYGEN_PATH subdirs CC CFLAGS CXX CXXFLAGS LD LDFLAGS AR ARFLAGS CPPFLAGS DEPENDENCY_RULES STRICTFLAG PARALLEL_FLAG RPATH LIB_PREFIX INSTALL INSTALL_DATA installfiles install_executable install_lib install_headers installdirs alltarget libsuffix dirstoclean package DRACO_DEPENDS DRACO_LIBS VENDOR_DEPENDS VENDOR_INC VENDOR_LIBS ARLIBS PKG_DEPENDS PKG_LIBS DRACO_TEST_DEPENDS DRACO_TEST_LIBS VENDOR_TEST_DEPENDS VENDOR_TEST_LIBS ARTESTLIBS test_alltarget test_flags test_scalar test_nprocs test_output_files configure_command package_top_srcdir LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MPI_INC MPI_LIB SPRNG_INC SPRNG_LIB PCG_LIB AZTEC_INC AZTEC_LIB GSL_INC GSL_LIB GSLCBLAS_INC GSLCBLAS_LIB TRILINOS_INC TRILINOS_LIB METIS_INC METIS_LIB LAPACK_LIB GANDOLF_LIB EOSPAC5_LIB GRACE_INC GRACE_LIB SPICA_INC SPICA_LIB latex_yes_no doxygen_output_top PYTHON_PATH PERL_PATH CVS_PATH GHOSTVIEW LATEX LATEXFLAGS BIBTEX BIBTEXFLAGS XDVI XDVIFLAGS DVIPS DVIPSFLAGS LP LPFLAGS DOXYGEN_PATH subdirs CC CFLAGS CXX CXXFLAGS LD LDFLAGS AR ARFLAGS CPPFLAGS DEPENDENCY_RULES STRICTFLAG PARALLEL_FLAG RPATH LIB_PREFIX INSTALL INSTALL_DATA installfiles install_executable install_lib install_headers installdirs alltarget libsuffix dirstoclean package DRACO_DEPENDS DRACO_LIBS VENDOR_DEPENDS VENDOR_INC VENDOR_LIBS ARLIBS PKG_DEPENDS PKG_LIBS DRACO_TEST_DEPENDS DRACO_TEST_LIBS VENDOR_TEST_DEPENDS VENDOR_TEST_LIBS ARTESTLIBS test_alltarget test_flags test_scalar test_nprocs test_output_files configure_command package_top_srcdir LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -870,6 +870,9 @@ Optional Packages:
   --with-grace=lib      determine the grace lib (grace_np is the default
   --with-grace-inc=DIR    tell where GRACE includes are (\${GRACE_INC_DIR} by default)
   --with-grace-lib=DIR    tell where GRACE libraries are (\${GRACE_LIB_DIR} by default)
+  --with-spica=yes                 spica is on by default
+  --with-spica-inc=DIR    tell where SPICA includes are (\${SPICA_INC_DIR} by default)
+  --with-spica-lib=DIR    tell where SPICA libraries are (\${SPICA_LIB_DIR} by default)
   --with-lib-prefix=library prefix
                           give prefix to libraries (default rtt_)
   --with-c4=scalar,mpi,shmem
@@ -2463,6 +2466,113 @@ _ACEOF
 
 
 
+# Check whether --with-spica or --without-spica was given.
+if test "${with_spica+set}" = set; then
+  withval="$with_spica"
+
+fi;
+
+
+
+
+
+# Check whether --with-spica-inc or --without-spica-inc was given.
+if test "${with_spica_inc+set}" = set; then
+  withval="$with_spica_inc"
+  if test $with_spica_inc != "no" ; then
+      if test $with_spica_inc = "yes" ; then
+         # following eval needed to remove possible '\' from \${SPICA_INC_DIR}
+         eval with_spica_inc=\${SPICA_INC_DIR}
+      fi
+
+      # this command removes double slashes and any trailing slash
+
+      with_spica_inc=`eval echo "$with_spica_inc" | sed 's%//*%/%g' | sed 's%/$%%'`
+      if test "$with_spica_inc:-null}" = "null" ; then
+         { echo "configure: error: --with-spica-inc directory is unset" 1>&2; \
+           exit 1; }
+      fi
+      if test ! -d $with_spica_inc ; then
+         { echo "configure: error: $with_spica_inc: invalid directory" 1>&2; \
+           exit 1; }
+      fi
+
+      # this sets up the shell variable, with the name of the CPPtoken,
+      # and that we later will do an AC_SUBST on.
+      SPICA_INC="${with_spica_inc}/"
+
+      # this defines the CPP macro with the directory and single slash appended.
+      cat >>confdefs.h <<_ACEOF
+#define SPICA_INC ${with_spica_inc}/
+_ACEOF
+
+      # print a message to the users (that can be turned off with --silent)
+
+      echo "SPICA_INC has been set to $SPICA_INC" 1>&6
+
+   fi
+fi;
+
+
+
+
+
+
+
+# Check whether --with-spica-lib or --without-spica-lib was given.
+if test "${with_spica_lib+set}" = set; then
+  withval="$with_spica_lib"
+  if test $with_spica_lib != "no" ; then
+      if test $with_spica_lib = "yes" ; then
+         # following eval needed to remove possible '\' from \${SPICA_LIB_DIR}
+         eval with_spica_lib=\${SPICA_LIB_DIR}
+      fi
+
+      # this command removes double slashes and any trailing slash
+
+      with_spica_lib=`eval echo "$with_spica_lib" | sed 's%//*%/%g' | sed 's%/$%%'`
+      if test "$with_spica_lib:-null}" = "null" ; then
+         { echo "configure: error: --with-spica-lib directory is unset" 1>&2; \
+           exit 1; }
+      fi
+      if test ! -d $with_spica_lib ; then
+         { echo "configure: error: $with_spica_lib: invalid directory" 1>&2; \
+           exit 1; }
+      fi
+
+      # this sets up the shell variable, with the name of the CPPtoken,
+      # and that we later will do an AC_SUBST on.
+      SPICA_LIB="${with_spica_lib}/"
+
+      # this defines the CPP macro with the directory and single slash appended.
+      cat >>confdefs.h <<_ACEOF
+#define SPICA_LIB ${with_spica_lib}/
+_ACEOF
+
+      # print a message to the users (that can be turned off with --silent)
+
+      echo "SPICA_LIB has been set to $SPICA_LIB" 1>&6
+
+   fi
+fi;
+
+
+
+
+   # determine if this package is needed for testing or for the
+   # package
+   vendor_spica=pkg
+
+   # define variable if spica is on
+   if test "${with_spica:=yes}" != no; then
+       cat >>confdefs.h <<\_ACEOF
+#define USE_SPICA 1
+_ACEOF
+
+   fi
+
+
+
 
 
 # Check whether --with-lib-prefix or --without-lib-prefix was given.
@@ -3868,6 +3978,8 @@ s,@GANDOLF_LIB@,$GANDOLF_LIB,;t t
 s,@EOSPAC5_LIB@,$EOSPAC5_LIB,;t t
 s,@GRACE_INC@,$GRACE_INC,;t t
 s,@GRACE_LIB@,$GRACE_LIB,;t t
+s,@SPICA_INC@,$SPICA_INC,;t t
+s,@SPICA_LIB@,$SPICA_LIB,;t t
 s,@latex_yes_no@,$latex_yes_no,;t t
 s,@doxygen_output_top@,$doxygen_output_top,;t t
 s,@PYTHON_PATH@,$PYTHON_PATH,;t t
