Updated the draco head directory with the revised draco build system.

diff --git a/draco_config b/draco_config
--- a/draco_config
+++ b/draco_config
@@ -1,20 +1,91 @@
 #!/bin/sh
-# usage: draco_conf prefix [stuff]
-# $Id$
+##---------------------------------------------------------------------------##
+## draco_config
+##
+## build aclocal.m4/configure scripts in each directory that has a
+## configure.ac
+##
+## if this is run in draco then no arguments are required; if not then
+## the relative (or absolute) path of the config directory must be
+## given, ie. if running in draco/src, ../draco_config ..
+##---------------------------------------------------------------------------##
 
-case $1 in
-    --*)
-      prefix=`pwd`
-      ;;
-    *)
-      prefix=$1
-      prefix=`cd $prefix; pwd`
-      shift
-      ;;
-esac
+## Build the configure scripts
 
-rootme=`dirname $0`
+build_config ()
+{
+    # build a configure script if configure.ac is present
+    if test -f configure.ac; then
+	echo ">>> Building configure in $1"
+	aclocal -I $config_dir
+	autoconf
+    fi
+}
 
-echo ${rootme}/configure --prefix=$prefix $*
-exec ${rootme}/configure --prefix=$prefix $*
+##---------------------------------------------------------------------------##
+
+## Recursively go through each directory
+
+dive()
+{
+    # find the directories
+    dirs=`ls`
+    real_dirs=''
+    for d in $dirs
+    do
+	if test -d $d && test "${d}" != CVS; then
+	    real_dirs="$real_dirs $d"
+	fi
+    done 
+
+    # dive into each directory
+    for d in $real_dirs
+    do
+	# dive and build configures
+	cd $d
+	dd=`pwd`
+	build_config $dd
+
+	# recursively dive to the next level
+	dive
+	
+    done
+
+    # once we hit bottom, come up one directory level
+    cd ..
+}
+
+##---------------------------------------------------------------------------##
+
+# home dir
+home=`pwd`
+
+# find the config directory
+
+if test -d config; then
+    config_dir="`pwd`/config"
+else
+    config_dir="`cd $1;pwd`/config"
+fi
+
+if test ! -d $config_dir; then
+    echo "Cannot find $config_dir"
+    exit 1
+fi
+
+cd $config_dir
+if test ! -f ac_dracoenv.m4; then
+    echo "Improperly specfied config directory."
+    exit 1
+fi
+
+# build the configures
+cd $home
+build_config $home
+dive
+
+##---------------------------------------------------------------------------##
+## end of draco_config
+##---------------------------------------------------------------------------##
+
 
