Added AC_MPI_SETUP(pkg) and AC_SHMEM_SETUP(pkg)

diff --git a/src/timestep/configure b/src/timestep/configure
--- a/src/timestep/configure
+++ b/src/timestep/configure
@@ -12,6 +12,19 @@ ac_help=
 ac_default_prefix=/usr/local
 # Any additions from configure.in:
 ac_help="$ac_help
+  --with-mpi=[vendor,mpich] 
+	                  determine MPI implementation (vendor by default)"
+ac_help="$ac_help
+  --with-mpi-inc[=DIR]    tell where MPI includes are (\${MPI_INC_DIR} by default)"
+ac_help="$ac_help
+  --with-mpi-lib[=DIR]    tell where MPI libs are (\${MPI_LIB_DIR} by default)"
+ac_help="$ac_help
+  --enable-shmem          turn on shmem (off by default)"
+ac_help="$ac_help
+  --with-shmem-inc[=DIR]    tell where SHMEM includes are (\${SHMEM_INC_DIR} by default)"
+ac_help="$ac_help
+  --with-shmem-lib[=DIR]    tell where SHMEM libs are (\${SHMEM_LIB_DIR} by default)"
+ac_help="$ac_help
   --with-c4[=scalar,mpi,shmem]   
 		          turn on c4 (default scalar) "
 ac_help="$ac_help
@@ -561,6 +574,258 @@ ac_configure=$ac_aux_dir/configure # This should be Cygnus configure.
 
 package="timestep"
 
+
+      # Check whether --with-mpi or --without-mpi was given.
+if test "${with_mpi+set}" = set; then
+  withval="$with_mpi"
+  :
+fi
+
+
+      
+        
+   
+ # Check whether --with-mpi-inc or --without-mpi-inc was given.
+if test "${with_mpi_inc+set}" = set; then
+  withval="$with_mpi_inc"
+  if test $with_mpi_inc != "no" ; then
+      if test $with_mpi_inc = "yes" ; then
+         # following eval needed to remove possible '\' from \${MPI_INC_DIR}
+         eval with_mpi_inc=\${MPI_INC_DIR}
+      fi
+
+      # this command removes double slashes and any trailing slash
+
+      with_mpi_inc=`eval echo "$with_mpi_inc" | sed 's%//*%/%g' | sed 's%/$%%'`
+      if test "$with_mpi_inc:-null}" = "null" ; then
+         { echo "configure: error: --with-mpi-inc directory is unset" 1>&2; \
+           exit 1; }
+      fi
+      if test ! -d $with_mpi_inc ; then
+         { echo "configure: error: $with_mpi_inc: invalid directory" 1>&2; \
+           exit 1; }
+      fi
+
+      # this sets up the shell variable, with the name of the CPPtoken,
+      # and that we later will do an AC_SUBST on.
+      MPI_INC="${with_mpi_inc}/"
+
+      # this defines the CPP macro with the directory and single slash appended.
+      cat >> confdefs.h <<EOF
+#define MPI_INC ${with_mpi_inc}/
+EOF
+
+      # print a message to the users (that can be turned off with --silent)
+
+      echo "MPI_INC has been set to $MPI_INC" 1>&6
+
+   fi
+fi
+
+
+   
+
+   
+        
+   
+ # Check whether --with-mpi-lib or --without-mpi-lib was given.
+if test "${with_mpi_lib+set}" = set; then
+  withval="$with_mpi_lib"
+  if test $with_mpi_lib != "no" ; then
+      if test $with_mpi_lib = "yes" ; then
+         # following eval needed to remove possible '\' from \${MPI_LIB_DIR}
+         eval with_mpi_lib=\${MPI_LIB_DIR}
+      fi
+
+      # this command removes double slashes and any trailing slash
+
+      with_mpi_lib=`eval echo "$with_mpi_lib" | sed 's%//*%/%g' | sed 's%/$%%'`
+      if test "$with_mpi_lib:-null}" = "null" ; then
+         { echo "configure: error: --with-mpi-lib directory is unset" 1>&2; \
+           exit 1; }
+      fi
+      if test ! -d $with_mpi_lib ; then
+         { echo "configure: error: $with_mpi_lib: invalid directory" 1>&2; \
+           exit 1; }
+      fi
+
+      # this sets up the shell variable, with the name of the CPPtoken,
+      # and that we later will do an AC_SUBST on.
+      MPI_LIB="${with_mpi_lib}/"
+
+      # this defines the CPP macro with the directory and single slash appended.
+      cat >> confdefs.h <<EOF
+#define MPI_LIB ${with_mpi_lib}/
+EOF
+
+      # print a message to the users (that can be turned off with --silent)
+
+      echo "MPI_LIB has been set to $MPI_LIB" 1>&6
+
+   fi
+fi
+
+
+   
+
+
+   # define MPI include path
+   if test -n "${MPI_INC}" ; then
+       # remember that MPI_INC has the final slash
+       MPI_H="\"${MPI_INC}mpi.h\""
+   elif test -z "${MPI_INC}" ; then
+       MPI_H="<mpi.h>"
+   fi
+   
+   # we define MPI_H regardless of whether a PATH is set
+   cat >> confdefs.h <<EOF
+#define MPI_H ${MPI_H}
+EOF
+
+   # determine if this package is needed for testing or for the
+   # package
+   vendor_mpi=pkg
+
+   # set default value for with_mpi which is no
+   if test "${with_mpi:=no}" = yes ; then 
+       with_mpi='vendor'
+   fi
+
+   # if the user sets MPI_INC and MPI_LIB directories then turn on  
+   # with_mpi and set it to vendor if with_mpi=no to begin with
+   if test "${with_mpi}" = no ; then
+       if test -n "${MPI_INC}" ; then
+	   with_mpi='vendor'
+       elif test -n "${MPI_LIB}" ; then
+	   with_mpi='vendor'
+       fi
+   fi
+
+            
+	
+      # Check whether --enable-shmem or --disable-shmem was given.
+if test "${enable_shmem+set}" = set; then
+  enableval="$enable_shmem"
+  :
+fi
+
+
+      
+        
+   
+ # Check whether --with-shmem-inc or --without-shmem-inc was given.
+if test "${with_shmem_inc+set}" = set; then
+  withval="$with_shmem_inc"
+  if test $with_shmem_inc != "no" ; then
+      if test $with_shmem_inc = "yes" ; then
+         # following eval needed to remove possible '\' from \${SHMEM_INC_DIR}
+         eval with_shmem_inc=\${SHMEM_INC_DIR}
+      fi
+
+      # this command removes double slashes and any trailing slash
+
+      with_shmem_inc=`eval echo "$with_shmem_inc" | sed 's%//*%/%g' | sed 's%/$%%'`
+      if test "$with_shmem_inc:-null}" = "null" ; then
+         { echo "configure: error: --with-shmem-inc directory is unset" 1>&2; \
+           exit 1; }
+      fi
+      if test ! -d $with_shmem_inc ; then
+         { echo "configure: error: $with_shmem_inc: invalid directory" 1>&2; \
+           exit 1; }
+      fi
+
+      # this sets up the shell variable, with the name of the CPPtoken,
+      # and that we later will do an AC_SUBST on.
+      SHMEM_INC="${with_shmem_inc}/"
+
+      # this defines the CPP macro with the directory and single slash appended.
+      cat >> confdefs.h <<EOF
+#define SHMEM_INC ${with_shmem_inc}/
+EOF
+
+      # print a message to the users (that can be turned off with --silent)
+
+      echo "SHMEM_INC has been set to $SHMEM_INC" 1>&6
+
+   fi
+fi
+
+
+   
+
+   
+        
+   
+ # Check whether --with-shmem-lib or --without-shmem-lib was given.
+if test "${with_shmem_lib+set}" = set; then
+  withval="$with_shmem_lib"
+  if test $with_shmem_lib != "no" ; then
+      if test $with_shmem_lib = "yes" ; then
+         # following eval needed to remove possible '\' from \${SHMEM_LIB_DIR}
+         eval with_shmem_lib=\${SHMEM_LIB_DIR}
+      fi
+
+      # this command removes double slashes and any trailing slash
+
+      with_shmem_lib=`eval echo "$with_shmem_lib" | sed 's%//*%/%g' | sed 's%/$%%'`
+      if test "$with_shmem_lib:-null}" = "null" ; then
+         { echo "configure: error: --with-shmem-lib directory is unset" 1>&2; \
+           exit 1; }
+      fi
+      if test ! -d $with_shmem_lib ; then
+         { echo "configure: error: $with_shmem_lib: invalid directory" 1>&2; \
+           exit 1; }
+      fi
+
+      # this sets up the shell variable, with the name of the CPPtoken,
+      # and that we later will do an AC_SUBST on.
+      SHMEM_LIB="${with_shmem_lib}/"
+
+      # this defines the CPP macro with the directory and single slash appended.
+      cat >> confdefs.h <<EOF
+#define SHMEM_LIB ${with_shmem_lib}/
+EOF
+
+      # print a message to the users (that can be turned off with --silent)
+
+      echo "SHMEM_LIB has been set to $SHMEM_LIB" 1>&6
+
+   fi
+fi
+
+
+   
+
+
+   # define SHMEM include path
+   if test -n "${SHMEM_INC}" ; then
+       # remember that SHMEM_INC has the final slash
+       SHMEM_H="\"${SHMEM_INC}shmem.h\""
+   elif test -z "${SHMEM_INC}" ; then
+       SHMEM_H="<mpp/shmem.h>"
+   fi
+   
+   # we define SHMEM_H regardless of whether a PATH is set
+   cat >> confdefs.h <<EOF
+#define SHMEM_H ${SHMEM_H}
+EOF
+
+   # determine if this package is needed for testing or for the
+   # package
+   vendor_shmem=pkg
+	
+   # if the user sets SHMEM_INC or SHMEM_LIB and enable_shmem=no
+   # then turn on enable_shmem
+   if test "${enable_shmem:=no}" = no ; then
+       if test -n "${SHMEM_INC}" ; then
+	   enable_shmem='yes'
+       elif test -n "${SHMEM_LIB}" ; then
+	   enable_shmem='yes'
+       fi
+   fi
+
+            
+
     install_headers="\${installheaders}"
    installdirs="${installdirs} \${includedir} \${includedir}/\${package}"
 
@@ -851,7 +1116,7 @@ fi
 # SVR4 /usr/ucb/install, which tries to use the nonexistent group "staff"
 # ./install, which can be erroneously created by make from ./install.sh.
 echo $ac_n "checking for a BSD compatible install""... $ac_c" 1>&6
-echo "configure:855: checking for a BSD compatible install" >&5
+echo "configure:1120: checking for a BSD compatible install" >&5
 if test -z "$INSTALL"; then
 if eval "test \"`echo '$''{'ac_cv_path_install'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -912,7 +1177,7 @@ else { echo "configure: error: can not run $ac_config_sub" 1>&2; exit 1; }
 fi
 
 echo $ac_n "checking host system type""... $ac_c" 1>&6
-echo "configure:916: checking host system type" >&5
+echo "configure:1181: checking host system type" >&5
 
 host_alias=$host
 case "$host_alias" in
@@ -936,7 +1201,7 @@ echo "$ac_t""$host" 1>&6
       # Extract the first word of "KCC", so it can be a program name with args.
 set dummy KCC; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:940: checking for $ac_word" >&5
+echo "configure:1205: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_CXX'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -965,7 +1230,7 @@ fi
    # Extract the first word of "KCC", so it can be a program name with args.
 set dummy KCC; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:969: checking for $ac_word" >&5
+echo "configure:1234: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_CC'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -997,7 +1262,7 @@ do
 # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1001: checking for $ac_word" >&5
+echo "configure:1266: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_CXX'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1028,7 +1293,7 @@ test -n "$CXX" || CXX="gcc"
 
 
 echo $ac_n "checking whether the C++ compiler ($CXX $CXXFLAGS $LDFLAGS) works""... $ac_c" 1>&6
-echo "configure:1032: checking whether the C++ compiler ($CXX $CXXFLAGS $LDFLAGS) works" >&5
+echo "configure:1297: checking whether the C++ compiler ($CXX $CXXFLAGS $LDFLAGS) works" >&5
 
 ac_ext=C
 # CXXFLAGS is not in ac_cpp because -g, -O, etc. are not valid cpp options.
@@ -1038,11 +1303,11 @@ ac_link='${CXX-g++} -o conftest $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $L
 cross_compiling=$ac_cv_prog_cxx_cross
 
 cat > conftest.$ac_ext <<EOF
-#line 1042 "configure"
+#line 1307 "configure"
 #include "confdefs.h"
 main(){return(0);}
 EOF
-if { (eval echo configure:1046: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:1311: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   ac_cv_prog_cxx_works=yes
   # If we can't run a trivial program, we are probably using a cross compiler.
   if (./conftest; exit) 2>/dev/null; then
@@ -1068,12 +1333,12 @@ if test $ac_cv_prog_cxx_works = no; then
   { echo "configure: error: installation or configuration problem: C++ compiler cannot create executables." 1>&2; exit 1; }
 fi
 echo $ac_n "checking whether the C++ compiler ($CXX $CXXFLAGS $LDFLAGS) is a cross-compiler""... $ac_c" 1>&6
-echo "configure:1072: checking whether the C++ compiler ($CXX $CXXFLAGS $LDFLAGS) is a cross-compiler" >&5
+echo "configure:1337: checking whether the C++ compiler ($CXX $CXXFLAGS $LDFLAGS) is a cross-compiler" >&5
 echo "$ac_t""$ac_cv_prog_cxx_cross" 1>&6
 cross_compiling=$ac_cv_prog_cxx_cross
 
 echo $ac_n "checking whether we are using GNU C++""... $ac_c" 1>&6
-echo "configure:1077: checking whether we are using GNU C++" >&5
+echo "configure:1342: checking whether we are using GNU C++" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_gxx'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1082,7 +1347,7 @@ else
   yes;
 #endif
 EOF
-if { ac_try='${CXX-g++} -E conftest.C'; { (eval echo configure:1086: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }; } | egrep yes >/dev/null 2>&1; then
+if { ac_try='${CXX-g++} -E conftest.C'; { (eval echo configure:1351: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }; } | egrep yes >/dev/null 2>&1; then
   ac_cv_prog_gxx=yes
 else
   ac_cv_prog_gxx=no
@@ -1097,7 +1362,7 @@ if test $ac_cv_prog_gxx = yes; then
   ac_save_CXXFLAGS="$CXXFLAGS"
   CXXFLAGS=
   echo $ac_n "checking whether ${CXX-g++} accepts -g""... $ac_c" 1>&6
-echo "configure:1101: checking whether ${CXX-g++} accepts -g" >&5
+echo "configure:1366: checking whether ${CXX-g++} accepts -g" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_cxx_g'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1163,7 +1428,7 @@ fi
        # Extract the first word of "gcc", so it can be a program name with args.
 set dummy gcc; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1167: checking for $ac_word" >&5
+echo "configure:1432: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_CC'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1192,7 +1457,7 @@ if test -z "$CC"; then
   # Extract the first word of "cc", so it can be a program name with args.
 set dummy cc; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1196: checking for $ac_word" >&5
+echo "configure:1461: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_CC'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1240,7 +1505,7 @@ fi
 fi
 
 echo $ac_n "checking whether the C compiler ($CC $CFLAGS $LDFLAGS) works""... $ac_c" 1>&6
-echo "configure:1244: checking whether the C compiler ($CC $CFLAGS $LDFLAGS) works" >&5
+echo "configure:1509: checking whether the C compiler ($CC $CFLAGS $LDFLAGS) works" >&5
 
 ac_ext=c
 # CFLAGS is not in ac_cpp because -g, -O, etc. are not valid cpp options.
@@ -1250,11 +1515,11 @@ ac_link='${CC-cc} -o conftest $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS 
 cross_compiling=$ac_cv_prog_cc_cross
 
 cat > conftest.$ac_ext <<EOF
-#line 1254 "configure"
+#line 1519 "configure"
 #include "confdefs.h"
 main(){return(0);}
 EOF
-if { (eval echo configure:1258: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:1523: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   ac_cv_prog_cc_works=yes
   # If we can't run a trivial program, we are probably using a cross compiler.
   if (./conftest; exit) 2>/dev/null; then
@@ -1274,12 +1539,12 @@ if test $ac_cv_prog_cc_works = no; then
   { echo "configure: error: installation or configuration problem: C compiler cannot create executables." 1>&2; exit 1; }
 fi
 echo $ac_n "checking whether the C compiler ($CC $CFLAGS $LDFLAGS) is a cross-compiler""... $ac_c" 1>&6
-echo "configure:1278: checking whether the C compiler ($CC $CFLAGS $LDFLAGS) is a cross-compiler" >&5
+echo "configure:1543: checking whether the C compiler ($CC $CFLAGS $LDFLAGS) is a cross-compiler" >&5
 echo "$ac_t""$ac_cv_prog_cc_cross" 1>&6
 cross_compiling=$ac_cv_prog_cc_cross
 
 echo $ac_n "checking whether we are using GNU C""... $ac_c" 1>&6
-echo "configure:1283: checking whether we are using GNU C" >&5
+echo "configure:1548: checking whether we are using GNU C" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_gcc'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1288,7 +1553,7 @@ else
   yes;
 #endif
 EOF
-if { ac_try='${CC-cc} -E conftest.c'; { (eval echo configure:1292: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }; } | egrep yes >/dev/null 2>&1; then
+if { ac_try='${CC-cc} -E conftest.c'; { (eval echo configure:1557: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }; } | egrep yes >/dev/null 2>&1; then
   ac_cv_prog_gcc=yes
 else
   ac_cv_prog_gcc=no
@@ -1303,7 +1568,7 @@ if test $ac_cv_prog_gcc = yes; then
   ac_save_CFLAGS="$CFLAGS"
   CFLAGS=
   echo $ac_n "checking whether ${CC-cc} accepts -g""... $ac_c" 1>&6
-echo "configure:1307: checking whether ${CC-cc} accepts -g" >&5
+echo "configure:1572: checking whether ${CC-cc} accepts -g" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_cc_g'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1335,7 +1600,7 @@ fi
       # Extract the first word of "ranlib", so it can be a program name with args.
 set dummy ranlib; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1339: checking for $ac_word" >&5
+echo "configure:1604: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_RANLIB'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1640,6 +1905,10 @@ s%@includedir@%$includedir%g
 s%@oldincludedir@%$oldincludedir%g
 s%@infodir@%$infodir%g
 s%@mandir@%$mandir%g
+s%@MPI_INC@%$MPI_INC%g
+s%@MPI_LIB@%$MPI_LIB%g
+s%@SHMEM_INC@%$SHMEM_INC%g
+s%@SHMEM_LIB@%$SHMEM_LIB%g
 s%@INSTALL_PROGRAM@%$INSTALL_PROGRAM%g
 s%@INSTALL_DATA@%$INSTALL_DATA%g
 s%@host@%$host%g
