o Installed the official release of STLport-5.0.0.  The stlport   library names have changed and I have updated the   config/ac_dracoenv.m4 script to reflect the new names.  You can   build draco against STLport by adding the configure option   --with-stlport=/codes/radtran/vendors/stlport/Linux

diff --git a/src/c4/configure b/src/c4/configure
--- a/src/c4/configure
+++ b/src/c4/configure
@@ -5377,57 +5377,44 @@ ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
    echo "$as_me:$LINENO: checking \"for stlport\"" >&5
 echo $ECHO_N "checking \"for stlport\"... $ECHO_C" >&6
    if test "${with_stlport:=no}" != no; then
-      if ! test -d "${with_stlport}/include/stlport"; then
-         { { echo "$as_me:$LINENO: error: \"Invalid directory ${with_stlport}/include/stlport\"" >&5
-echo "$as_me: error: \"Invalid directory ${with_stlport}/include/stlport\"" >&2;}
+      if ! test -d "${with_stlport}/include"; then
+         { { echo "$as_me:$LINENO: error: \"Invalid directory ${with_stlport}/include\"" >&5
+echo "$as_me: error: \"Invalid directory ${with_stlport}/include\"" >&2;}
    { (exit 1); exit 1; }; }
       fi
-      CPPFLAGS="-I${with_stlport}/include/stlport ${CPPFLAGS}"
-      CXXFLAGS="-I${with_stlport}/include/stlport ${CXXFLAGS}"
+      CPPFLAGS="-I${with_stlport}/include ${CPPFLAGS}"
+      CXXFLAGS="-pthread -I${with_stlport}/include ${CXXFLAGS}"
       echo "$as_me:$LINENO: result: \"-I${with_stlport}/include added to CXXFLAGS.\"" >&5
 echo "${ECHO_T}\"-I${with_stlport}/include added to CXXFLAGS.\"" >&6
-      case $with_cxx in
-      sgi)
-         stlport_libname='mipspro'
-         stlport_xlinker=' '
-         ;;
-      gcc)          stlport_libname='gcc'
-         stlport_xlinker="-Xlinker"
-         ;;
-      *)
-         { { echo "$as_me:$LINENO: error: \"stlport not available with this compiler.\"" >&5
-echo "$as_me: error: \"stlport not available with this compiler.\"" >&2;}
-   { (exit 1); exit 1; }; }
-         ;;
-      esac
-      echo "$as_me:$LINENO: checking \"for debug stlport mode\"" >&5
+
+                  echo "$as_me:$LINENO: checking \"for debug stlport mode\"" >&5
 echo $ECHO_N "checking \"for debug stlport mode\"... $ECHO_C" >&6
       if test "${enable_debug:-yes}" = yes; then
-         if ! test -r "${with_stlport}/lib/libstlport_${stlport_libname}_stldebug.a"; then
-            { { echo "$as_me:$LINENO: error: \"Invalid library ${with_stlport}/lib/libstlport_${stlport_libname}_stldebug.a\"" >&5
-echo "$as_me: error: \"Invalid library ${with_stlport}/lib/libstlport_${stlport_libname}_stldebug.a\"" >&2;}
+         if ! test -r "${with_stlport}/lib/libstlportstlg.so"; then
+            { { echo "$as_me:$LINENO: error: \"Invalid library ${with_stlport}/lib/libstlportstlg.so\"" >&5
+echo "$as_me: error: \"Invalid library ${with_stlport}/lib/libstlportstlg.so\"" >&2;}
    { (exit 1); exit 1; }; }
          fi
-         LIBS="-L${with_stlport}/lib -lstlport_${stlport_libname}_stldebug ${LIBS}"
+         LIBS="-L${with_stlport}/lib -lstlportstlg ${LIBS}"
          CXXFLAGS="${CXXFLAGS} -D_STLP_DEBUG"
          echo "$as_me:$LINENO: result: \"yes\"" >&5
 echo "${ECHO_T}\"yes\"" >&6
       else
-         if ! test -r "${with_stlport}/lib/libstlport_${stlport_libname}.a"; then
-            { { echo "$as_me:$LINENO: error: \"Invalid library ${with_stlport}/lib/libstlport_${stlport_libname}.a\"" >&5
-echo "$as_me: error: \"Invalid library ${with_stlport}/lib/libstlport_${stlport_libname}.a\"" >&2;}
+                  if ! test -r "${with_stlport}/lib/libstlport.so"; then
+            { { echo "$as_me:$LINENO: error: \"Invalid library ${with_stlport}/lib/libstlport.so\"" >&5
+echo "$as_me: error: \"Invalid library ${with_stlport}/lib/libstlport.so\"" >&2;}
    { (exit 1); exit 1; }; }
          fi
-         LIBS="-L${with_stlport}/lib -lstlport_${stlport_libname} ${LIBS}"
+         LIBS="-L${with_stlport}/lib -lstlport ${LIBS}"
          echo "$as_me:$LINENO: result: \"no\"" >&5
 echo "${ECHO_T}\"no\"" >&6
       fi
 
       echo "$as_me:$LINENO: checking \"for RPATH mods for stlport\"" >&5
 echo $ECHO_N "checking \"for RPATH mods for stlport\"... $ECHO_C" >&6
-      RPATH="${stlport_xlinker} -rpath ${with_stlport}/lib ${RPATH}"
-      echo "$as_me:$LINENO: result: \"Added ${stlport_xlinker} -rpath ${with_stlport}/lib to RPATH\"" >&5
-echo "${ECHO_T}\"Added ${stlport_xlinker} -rpath ${with_stlport}/lib to RPATH\"" >&6
+      RPATH="-Xlinker -rpath ${with_stlport}/lib ${RPATH}"
+      echo "$as_me:$LINENO: result: \"Added -Xlinker -rpath ${with_stlport}/lib to RPATH\"" >&5
+echo "${ECHO_T}\"Added -Xlinker -rpath ${with_stlport}/lib to RPATH\"" >&6
 
    elif test "${with_stlport}" = yes; then
       { { echo "$as_me:$LINENO: error: \"Must define path to stlport when using --with-stlport=dir\"" >&5
