ran draco_config

diff --git a/src/c4/configure b/src/c4/configure
--- a/src/c4/configure
+++ b/src/c4/configure
@@ -4575,6 +4575,10 @@ echo $ECHO_N "checking \"configuration of ${CXX}/${CC} compilers\"... $ECHO_C" >
    powerpc-apple-darwin*)
    ;;
 
+   # COMPAQ -> CXX
+   alpha*-dec-osf*)
+   ;;
+
    # EVERYTHING ELSE -> linux?
    *)
       if test -n "${GCC_LIB_DIR}"; then
@@ -4686,7 +4690,13 @@ echo $ECHO_N "checking \"configuration of ${CXX}/${CC} compilers\"... $ECHO_C" >
    if test "${enable_shared}" = yes ; then
        AR="${CXX}"
        ARFLAGS="-shared -nocxxstd -expect_unresolved '*3td*' "
-       ARFLAGS="${ARFLAGS} -expect_unresolved '*8_RWrwstd*' -o"
+       ARFLAGS="${ARFLAGS} -expect_unresolved '*8_RWrwstd*' "
+       ARFLAGS="${ARFLAGS} -expect_unresolved '*ios_base*' "
+       ARFLAGS="${ARFLAGS} -expect_unresolved '*basic_ostream*' "
+       ARFLAGS="${ARFLAGS} -expect_unresolved '*basic_string*' "
+       ARFLAGS="${ARFLAGS} -expect_unresolved '*cout*' "
+       ARFLAGS="${ARFLAGS} -expect_unresolved '*cerr*' "
+       ARFLAGS="${ARFLAGS} -o"
    else
        AR='ar'
        ARFLAGS='cr'
@@ -6689,6 +6699,7 @@ echo "${ECHO_T}\"no vendor lib dirs defined\"" >&6
 
 
        rptrigger=rpath
+       dilem=space
 
        if test "${enable_shared}" = yes ; then
 
@@ -6696,13 +6707,17 @@ echo "${ECHO_T}\"no vendor lib dirs defined\"" >&6
 	   RANLIB=':'
 
 	   # the g++/icc rpath needs Xlinker in front of it
-	   if test "${CXX}" = g++ || test "${CXX}" = icc; then
+           if test "${dilem}" = "space"; then
 	       RPATHA="-Xlinker -${rptrigger} \${curdir}"
 	       RPATHB="-Xlinker -${rptrigger} \${curdir}/.."
 	       RPATHC="-Xlinker -${rptrigger} \${libdir}"
 	       RPATH="${RPATHA} ${RPATHB} ${RPATHC} ${RPATH}"
-	   else
+           elif test "${dilem}" = "colon"; then
 	       RPATH="-${rptrigger} \${curdir}:\${curdir}/..:\${libdir} ${RPATH}"
+           else
+               { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
+echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
+   { (exit 1); exit 1; }; }
 	   fi
        fi
 
@@ -6710,14 +6725,18 @@ echo "${ECHO_T}\"no vendor lib dirs defined\"" >&6
        for vendor_dir in ${VENDOR_LIB_DIRS};
        do
 	   # if we are using gcc then add xlinker
-	   if test "${CXX}" = g++ || test "${CXX}" = icc; then
+           if test "${dilem}" = "space"; then
 	       RPATH="-Xlinker -${rptrigger} ${vendor_dir} ${RPATH}"
-
 	   # else we just add the rpath
-	   else
+           elif test "${dilem}" = "colon"; then
 	       RPATH="-${rptrigger} ${vendor_dir} ${RPATH}"
+           else
+               { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
+echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
+   { (exit 1); exit 1; }; }
 	   fi
        done
+
 
 
        # add the intel math library for better performance when
@@ -7636,6 +7655,7 @@ echo "${ECHO_T}\"no vendor lib dirs defined\"" >&6
 
 
        rptrigger=rpath
+       dilem=space
 
        if test "${enable_shared}" = yes ; then
 
@@ -7643,13 +7663,17 @@ echo "${ECHO_T}\"no vendor lib dirs defined\"" >&6
 	   RANLIB=':'
 
 	   # the g++/icc rpath needs Xlinker in front of it
-	   if test "${CXX}" = g++ || test "${CXX}" = icc; then
+           if test "${dilem}" = "space"; then
 	       RPATHA="-Xlinker -${rptrigger} \${curdir}"
 	       RPATHB="-Xlinker -${rptrigger} \${curdir}/.."
 	       RPATHC="-Xlinker -${rptrigger} \${libdir}"
 	       RPATH="${RPATHA} ${RPATHB} ${RPATHC} ${RPATH}"
-	   else
+           elif test "${dilem}" = "colon"; then
 	       RPATH="-${rptrigger} \${curdir}:\${curdir}/..:\${libdir} ${RPATH}"
+           else
+               { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
+echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
+   { (exit 1); exit 1; }; }
 	   fi
        fi
 
@@ -7657,14 +7681,18 @@ echo "${ECHO_T}\"no vendor lib dirs defined\"" >&6
        for vendor_dir in ${VENDOR_LIB_DIRS};
        do
 	   # if we are using gcc then add xlinker
-	   if test "${CXX}" = g++ || test "${CXX}" = icc; then
+           if test "${dilem}" = "space"; then
 	       RPATH="-Xlinker -${rptrigger} ${vendor_dir} ${RPATH}"
-
 	   # else we just add the rpath
-	   else
+           elif test "${dilem}" = "colon"; then
 	       RPATH="-${rptrigger} ${vendor_dir} ${RPATH}"
+           else
+               { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
+echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
+   { (exit 1); exit 1; }; }
 	   fi
        done
+
 
 
 
@@ -8680,6 +8708,7 @@ echo "${ECHO_T}\"no vendor lib dirs defined\"" >&6
 
 
        rptrigger=rpath
+       dilem=colon
 
        if test "${enable_shared}" = yes ; then
 
@@ -8687,13 +8716,17 @@ echo "${ECHO_T}\"no vendor lib dirs defined\"" >&6
 	   RANLIB=':'
 
 	   # the g++/icc rpath needs Xlinker in front of it
-	   if test "${CXX}" = g++ || test "${CXX}" = icc; then
+           if test "${dilem}" = "space"; then
 	       RPATHA="-Xlinker -${rptrigger} \${curdir}"
 	       RPATHB="-Xlinker -${rptrigger} \${curdir}/.."
 	       RPATHC="-Xlinker -${rptrigger} \${libdir}"
 	       RPATH="${RPATHA} ${RPATHB} ${RPATHC} ${RPATH}"
-	   else
+           elif test "${dilem}" = "colon"; then
 	       RPATH="-${rptrigger} \${curdir}:\${curdir}/..:\${libdir} ${RPATH}"
+           else
+               { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
+echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
+   { (exit 1); exit 1; }; }
 	   fi
        fi
 
@@ -8701,14 +8734,18 @@ echo "${ECHO_T}\"no vendor lib dirs defined\"" >&6
        for vendor_dir in ${VENDOR_LIB_DIRS};
        do
 	   # if we are using gcc then add xlinker
-	   if test "${CXX}" = g++ || test "${CXX}" = icc; then
+           if test "${dilem}" = "space"; then
 	       RPATH="-Xlinker -${rptrigger} ${vendor_dir} ${RPATH}"
-
 	   # else we just add the rpath
-	   else
+           elif test "${dilem}" = "colon"; then
 	       RPATH="-${rptrigger} ${vendor_dir} ${RPATH}"
+           else
+               { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
+echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
+   { (exit 1); exit 1; }; }
 	   fi
        done
+
 
 
 
@@ -8801,13 +8838,17 @@ _ACEOF
        #
 
        #
-       # gandolf, eospac, pcg, udm require -lfor on the link line.
+       # libfor.a requirements:
+       # GANDOLF, EOSPAC, PCG, BLACS, udm require -lfor on the link line.
        #
 
-       echo "$as_me:$LINENO: checking \"libfortran requirements\"" >&5
-echo $ECHO_N "checking \"libfortran requirements\"... $ECHO_C" >&6
-       if test -n "${vendor_gandolf}" || test -n "${vendor_eospac}" ||
-          test -n "${vendor_pcg}" || test -n "${vendor_udm}"; then
+       echo "$as_me:$LINENO: checking \"libfor.a requirements\"" >&5
+echo $ECHO_N "checking \"libfor.a requirements\"... $ECHO_C" >&6
+       if test -n "${vendor_gandolf}" ||
+          test -n "${vendor_eospac}"  ||
+          test -n "${vendor_pcg}"     ||
+          test -n "${vendor_udm}"     ||
+          test -n "${vendor_blacs}"; then
            LIBS="${LIBS} -lfor"
            echo "$as_me:$LINENO: result: \"-lfor added to LIBS\"" >&5
 echo "${ECHO_T}\"-lfor added to LIBS\"" >&6
@@ -8817,16 +8858,18 @@ echo "${ECHO_T}\"not needed\"" >&6
        fi
 
        #
-       # end of gandolf/libfortran setup
+       # end of libfor.a requirements
        #
 
        #
-       # libpcg/libudm/libfmpi setup
+       # libpcg/libudm/libfmpi setup (libfmpi.a requirements)
        #
 
        echo "$as_me:$LINENO: checking \"libfmpi requirements\"" >&5
 echo $ECHO_N "checking \"libfmpi requirements\"... $ECHO_C" >&6
-       if test -n "${vendor_pcg}" || test "${with_udm}" = mpi; then
+       if test -n "${vendor_pcg}"  ||
+          test "${with_udm}" = mpi ||
+          test -n "${vendor_blacs}" ; then
            LIBS="${LIBS} -lfmpi"
            echo "$as_me:$LINENO: result: \"-lfmpi added to LIBS\"" >&5
 echo "${ECHO_T}\"-lfmpi added to LIBS\"" >&6
@@ -9668,6 +9711,7 @@ echo "${ECHO_T}\"no vendor lib dirs defined\"" >&6
 
 
        rptrigger=rpath
+       dilem=colon
 
        if test "${enable_shared}" = yes ; then
 
@@ -9675,13 +9719,17 @@ echo "${ECHO_T}\"no vendor lib dirs defined\"" >&6
 	   RANLIB=':'
 
 	   # the g++/icc rpath needs Xlinker in front of it
-	   if test "${CXX}" = g++ || test "${CXX}" = icc; then
+           if test "${dilem}" = "space"; then
 	       RPATHA="-Xlinker -${rptrigger} \${curdir}"
 	       RPATHB="-Xlinker -${rptrigger} \${curdir}/.."
 	       RPATHC="-Xlinker -${rptrigger} \${libdir}"
 	       RPATH="${RPATHA} ${RPATHB} ${RPATHC} ${RPATH}"
-	   else
+           elif test "${dilem}" = "colon"; then
 	       RPATH="-${rptrigger} \${curdir}:\${curdir}/..:\${libdir} ${RPATH}"
+           else
+               { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
+echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
+   { (exit 1); exit 1; }; }
 	   fi
        fi
 
@@ -9689,14 +9737,18 @@ echo "${ECHO_T}\"no vendor lib dirs defined\"" >&6
        for vendor_dir in ${VENDOR_LIB_DIRS};
        do
 	   # if we are using gcc then add xlinker
-	   if test "${CXX}" = g++ || test "${CXX}" = icc; then
+           if test "${dilem}" = "space"; then
 	       RPATH="-Xlinker -${rptrigger} ${vendor_dir} ${RPATH}"
-
 	   # else we just add the rpath
-	   else
+           elif test "${dilem}" = "colon"; then
 	       RPATH="-${rptrigger} ${vendor_dir} ${RPATH}"
+           else
+               { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
+echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
+   { (exit 1); exit 1; }; }
 	   fi
        done
+
 
 
 
@@ -11550,6 +11602,7 @@ echo "${ECHO_T}\"no vendor lib dirs defined\"" >&6
 
 
        rptrigger=R
+       dilem=space
 
        if test "${enable_shared}" = yes ; then
 
@@ -11557,13 +11610,17 @@ echo "${ECHO_T}\"no vendor lib dirs defined\"" >&6
 	   RANLIB=':'
 
 	   # the g++/icc rpath needs Xlinker in front of it
-	   if test "${CXX}" = g++ || test "${CXX}" = icc; then
+           if test "${dilem}" = "space"; then
 	       RPATHA="-Xlinker -${rptrigger} \${curdir}"
 	       RPATHB="-Xlinker -${rptrigger} \${curdir}/.."
 	       RPATHC="-Xlinker -${rptrigger} \${libdir}"
 	       RPATH="${RPATHA} ${RPATHB} ${RPATHC} ${RPATH}"
-	   else
+           elif test "${dilem}" = "colon"; then
 	       RPATH="-${rptrigger} \${curdir}:\${curdir}/..:\${libdir} ${RPATH}"
+           else
+               { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
+echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
+   { (exit 1); exit 1; }; }
 	   fi
        fi
 
@@ -11571,14 +11628,18 @@ echo "${ECHO_T}\"no vendor lib dirs defined\"" >&6
        for vendor_dir in ${VENDOR_LIB_DIRS};
        do
 	   # if we are using gcc then add xlinker
-	   if test "${CXX}" = g++ || test "${CXX}" = icc; then
+           if test "${dilem}" = "space"; then
 	       RPATH="-Xlinker -${rptrigger} ${vendor_dir} ${RPATH}"
-
 	   # else we just add the rpath
-	   else
+           elif test "${dilem}" = "colon"; then
 	       RPATH="-${rptrigger} ${vendor_dir} ${RPATH}"
+           else
+               { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
+echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
+   { (exit 1); exit 1; }; }
 	   fi
        done
+
 
 
    ;;
@@ -11587,6 +11648,11 @@ echo "${ECHO_T}\"no vendor lib dirs defined\"" >&6
    # MAC OS X/DARWIN SETUP
    # *********************
    powerpc-apple-darwin*)
+
+       # dependency rules for IBM visual age compiler are complex
+       if test "${with_cxx}" = ibm; then
+	   DEPENDENCY_RULES='Makefile.dep.xlC.darwin'
+       fi
 
        # print out cpu message
        echo "$as_me:$LINENO: checking \"host platform cpu\"" >&5
@@ -11628,7 +11694,13 @@ _ACEOF
 echo "$as_me: g++ -ansi option set to allow long long type!" >&6;}
                STRICTFLAG="$STRICTFLAG -Wno-long-long"
            ;;
-
+  	   ibm)
+	       { echo "$as_me:$LINENO: WARNING: \"xlC set to allow long long\"" >&5
+echo "$as_me: WARNING: \"xlC set to allow long long\"" >&2;}
+	       STRICTFLAG="-qlanglvl=extended"
+	       CFLAGS="${CFLAGS} -qlonglong"
+	       CXXFLAGS="${CXXFLAGS} -qlonglong"
+	   ;;
            # catchall
            *)
                # do nothing
