o Configure files updated to reflect recent change in   ac_platforms.m4.

diff --git a/src/ds++/configure b/src/ds++/configure
--- a/src/ds++/configure
+++ b/src/ds++/configure
@@ -271,7 +271,7 @@ PACKAGE_STRING=
 PACKAGE_BUGREPORT=
 
 ac_unique_file="SP.hh"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS latex_yes_no doxygen_output_top build build_cpu build_vendor build_os host host_cpu host_vendor host_os PYTHON_PATH PERL_PATH CVS_PATH GHOSTVIEW LATEX LATEXFLAGS BIBTEX BIBTEXFLAGS XDVI XDVIFLAGS DVIPS DVIPSFLAGS LP LPFLAGS DOXYGEN_PATH F90 F90FREE F90FIXED F90FLAGS MODFLAG CXX CC GCC_BIN RANLIB ac_ct_RANLIB CFLAGS CXXFLAGS LD LDFLAGS AR ARFLAGS CPPFLAGS DEPENDENCY_RULES STRICTFLAG PARALLEL_FLAG RPATH LIB_PREFIX INSTALL INSTALL_DATA installfiles install_executable install_lib install_headers installdirs alltarget libsuffix dirstoclean package DRACO_DEPENDS DRACO_LIBS VENDOR_DEPENDS VENDOR_INC VENDOR_LIBS ARLIBS PKG_DEPENDS PKG_LIBS DRACO_TEST_DEPENDS DRACO_TEST_LIBS VENDOR_TEST_DEPENDS VENDOR_TEST_LIBS ARTESTLIBS test_alltarget test_flags test_scalar test_nprocs test_output_files configure_command package_top_srcdir number doxygen_input doxygen_examples doxygen_html_output doxygen_latex_output DOXYGEN_TAGFILES rel_package_html header_dir autodoc_dir FLEXELINT_PATH DOTCMD PS2PDF LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS latex_yes_no doxygen_output_top build build_cpu build_vendor build_os host host_cpu host_vendor host_os PYTHON_PATH PERL_PATH CVS_PATH GHOSTVIEW LATEX LATEXFLAGS BIBTEX BIBTEXFLAGS XDVI XDVIFLAGS PS2PDF DOTCMD DVIPS DVIPSFLAGS LP LPFLAGS DOXYGEN_PATH F90 F90FREE F90FIXED F90FLAGS MODFLAG CXX CC GCC_BIN RANLIB ac_ct_RANLIB CFLAGS CXXFLAGS LD LDFLAGS AR ARFLAGS CPPFLAGS DEPENDENCY_RULES STRICTFLAG PARALLEL_FLAG RPATH LIB_PREFIX INSTALL INSTALL_DATA installfiles install_executable install_lib install_headers installdirs alltarget libsuffix dirstoclean package DRACO_DEPENDS DRACO_LIBS VENDOR_DEPENDS VENDOR_INC VENDOR_LIBS ARLIBS PKG_DEPENDS PKG_LIBS DRACO_TEST_DEPENDS DRACO_TEST_LIBS VENDOR_TEST_DEPENDS VENDOR_TEST_LIBS ARTESTLIBS test_alltarget test_flags test_scalar test_nprocs test_output_files configure_command package_top_srcdir number doxygen_input doxygen_examples doxygen_html_output doxygen_latex_output DOXYGEN_TAGFILES rel_package_html header_dir autodoc_dir FLEXELINT_PATH LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -2000,6 +2000,98 @@ test -n "$XDVI" || XDVI="null"
 echo "$as_me: WARNING: \"No valid xdvi found!\"" >&2;}
    fi
 
+
+      for ac_prog in ps2pdf
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_PS2PDF+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$PS2PDF"; then
+  ac_cv_prog_PS2PDF="$PS2PDF" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_PS2PDF="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+PS2PDF=$ac_cv_prog_PS2PDF
+if test -n "$PS2PDF"; then
+  echo "$as_me:$LINENO: result: $PS2PDF" >&5
+echo "${ECHO_T}$PS2PDF" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$PS2PDF" && break
+done
+test -n "$PS2PDF" || PS2PDF="null"
+
+   if test "${PS2PDF}" = null ; then
+       { echo "$as_me:$LINENO: WARNING: \"No valid ps2pdf found!\"" >&5
+echo "$as_me: WARNING: \"No valid ps2pdf found!\"" >&2;}
+   fi
+
+      for ac_prog in dot
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_DOTCMD+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$DOTCMD"; then
+  ac_cv_prog_DOTCMD="$DOTCMD" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_DOTCMD="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+DOTCMD=$ac_cv_prog_DOTCMD
+if test -n "$DOTCMD"; then
+  echo "$as_me:$LINENO: result: $DOTCMD" >&5
+echo "${ECHO_T}$DOTCMD" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$DOTCMD" && break
+done
+test -n "$DOTCMD" || DOTCMD="null"
+
+   if test "${DOTCMD}" = null ; then
+       { echo "$as_me:$LINENO: WARNING: \"No valid dot found!\"" >&5
+echo "$as_me: WARNING: \"No valid dot found!\"" >&2;}
+   fi
 
       for ac_prog in dvips
 do
@@ -5946,7 +6038,6 @@ _ACEOF
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_gsl}"; then
 
@@ -5986,7 +6077,6 @@ _ACEOF
        VENDOR_INC_DIRS="${VENDOR_INC_DIRS} ${GSL_INC}"
 
    fi
-
 
 
 
@@ -6064,7 +6154,6 @@ _ACEOF
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${PCG_LIB}"
 
    fi
-
 
 
    # set up the libraries and include path
@@ -6149,7 +6238,6 @@ _ACEOF
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_blacs}" ; then
 
@@ -6184,7 +6272,6 @@ _ACEOF
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${BLACS_LIB}"
 
    fi
-
 
 
    # set up lapack libraries
@@ -6694,19 +6781,21 @@ echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
        fi
 
        # add vendors to rpath
-       for vendor_dir in ${VENDOR_LIB_DIRS};
-       do
-           if test "${dilem}" = "space"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "nospace"; then
-	       RPATH="${rptrigger}${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "colon"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           else
-               { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
+       for vendor_dir in ${VENDOR_LIB_DIRS}; do
+                      so_libs=`ls ${vendor_dir}/*.so 2>/dev/null`
+           if test ! "${so_libs:-none}" = "none"; then
+              if test "${dilem}" = "space"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "nospace"; then
+	          RPATH="${rptrigger}${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "colon"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              else
+                  { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
 echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
    { (exit 1); exit 1; }; }
-	   fi
+   	      fi
+           fi
        done
 
 
@@ -6741,19 +6830,21 @@ echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
        fi
 
        # add vendors to rpath
-       for vendor_dir in ${VENDOR_LIB_DIRS};
-       do
-           if test "${dilem}" = "space"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "nospace"; then
-	       RPATH="${rptrigger}${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "colon"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           else
-               { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
+       for vendor_dir in ${VENDOR_LIB_DIRS}; do
+                      so_libs=`ls ${vendor_dir}/*.so 2>/dev/null`
+           if test ! "${so_libs:-none}" = "none"; then
+              if test "${dilem}" = "space"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "nospace"; then
+	          RPATH="${rptrigger}${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "colon"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              else
+                  { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
 echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
    { (exit 1); exit 1; }; }
-	   fi
+   	      fi
+           fi
        done
 
 
@@ -6970,7 +7061,6 @@ echo "${ECHO_T}\"not needed\"" >&6
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_gsl}"; then
 
@@ -7010,7 +7100,6 @@ echo "${ECHO_T}\"not needed\"" >&6
        VENDOR_INC_DIRS="${VENDOR_INC_DIRS} ${GSL_INC}"
 
    fi
-
 
 
 
@@ -7088,7 +7177,6 @@ echo "${ECHO_T}\"not needed\"" >&6
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${PCG_LIB}"
 
    fi
-
 
 
    # set up the libraries and include path
@@ -7173,7 +7261,6 @@ echo "${ECHO_T}\"not needed\"" >&6
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_blacs}" ; then
 
@@ -7208,7 +7295,6 @@ echo "${ECHO_T}\"not needed\"" >&6
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${BLACS_LIB}"
 
    fi
-
 
 
    # set up lapack libraries
@@ -7715,19 +7801,21 @@ echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
        fi
 
        # add vendors to rpath
-       for vendor_dir in ${VENDOR_LIB_DIRS};
-       do
-           if test "${dilem}" = "space"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "nospace"; then
-	       RPATH="${rptrigger}${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "colon"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           else
-               { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
+       for vendor_dir in ${VENDOR_LIB_DIRS}; do
+                      so_libs=`ls ${vendor_dir}/*.so 2>/dev/null`
+           if test ! "${so_libs:-none}" = "none"; then
+              if test "${dilem}" = "space"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "nospace"; then
+	          RPATH="${rptrigger}${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "colon"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              else
+                  { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
 echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
    { (exit 1); exit 1; }; }
-	   fi
+   	      fi
+           fi
        done
 
 
@@ -7968,7 +8056,6 @@ echo "${ECHO_T}\"not needed\"" >&6
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_gsl}"; then
 
@@ -8008,7 +8095,6 @@ echo "${ECHO_T}\"not needed\"" >&6
        VENDOR_INC_DIRS="${VENDOR_INC_DIRS} ${GSL_INC}"
 
    fi
-
 
 
 
@@ -8086,7 +8172,6 @@ echo "${ECHO_T}\"not needed\"" >&6
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${PCG_LIB}"
 
    fi
-
 
 
    # set up the libraries and include path
@@ -8171,7 +8256,6 @@ echo "${ECHO_T}\"not needed\"" >&6
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_blacs}" ; then
 
@@ -8206,7 +8290,6 @@ echo "${ECHO_T}\"not needed\"" >&6
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${BLACS_LIB}"
 
    fi
-
 
 
    # set up lapack libraries
@@ -8713,19 +8796,21 @@ echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
        fi
 
        # add vendors to rpath
-       for vendor_dir in ${VENDOR_LIB_DIRS};
-       do
-           if test "${dilem}" = "space"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "nospace"; then
-	       RPATH="${rptrigger}${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "colon"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           else
-               { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
+       for vendor_dir in ${VENDOR_LIB_DIRS}; do
+                      so_libs=`ls ${vendor_dir}/*.so 2>/dev/null`
+           if test ! "${so_libs:-none}" = "none"; then
+              if test "${dilem}" = "space"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "nospace"; then
+	          RPATH="${rptrigger}${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "colon"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              else
+                  { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
 echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
    { (exit 1); exit 1; }; }
-	   fi
+   	      fi
+           fi
        done
 
 
@@ -9021,7 +9106,6 @@ _ACEOF
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_gsl}"; then
 
@@ -9061,7 +9145,6 @@ _ACEOF
        VENDOR_INC_DIRS="${VENDOR_INC_DIRS} ${GSL_INC}"
 
    fi
-
 
 
 
@@ -9139,7 +9222,6 @@ _ACEOF
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${PCG_LIB}"
 
    fi
-
 
 
    # set up the libraries and include path
@@ -9224,7 +9306,6 @@ _ACEOF
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_blacs}" ; then
 
@@ -9259,7 +9340,6 @@ _ACEOF
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${BLACS_LIB}"
 
    fi
-
 
 
    # set up lapack libraries
@@ -9766,19 +9846,21 @@ echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
        fi
 
        # add vendors to rpath
-       for vendor_dir in ${VENDOR_LIB_DIRS};
-       do
-           if test "${dilem}" = "space"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "nospace"; then
-	       RPATH="${rptrigger}${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "colon"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           else
-               { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
+       for vendor_dir in ${VENDOR_LIB_DIRS}; do
+                      so_libs=`ls ${vendor_dir}/*.so 2>/dev/null`
+           if test ! "${so_libs:-none}" = "none"; then
+              if test "${dilem}" = "space"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "nospace"; then
+	          RPATH="${rptrigger}${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "colon"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              else
+                  { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
 echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
    { (exit 1); exit 1; }; }
-	   fi
+   	      fi
+           fi
        done
 
 
@@ -9989,7 +10071,6 @@ echo "$as_me: WARNING: \"xlC set to allow long long\"" >&2;}
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_gsl}"; then
 
@@ -10029,7 +10110,6 @@ echo "$as_me: WARNING: \"xlC set to allow long long\"" >&2;}
        VENDOR_INC_DIRS="${VENDOR_INC_DIRS} ${GSL_INC}"
 
    fi
-
 
 
 
@@ -10107,7 +10187,6 @@ echo "$as_me: WARNING: \"xlC set to allow long long\"" >&2;}
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${PCG_LIB}"
 
    fi
-
 
 
    # set up the libraries and include path
@@ -10192,7 +10271,6 @@ echo "$as_me: WARNING: \"xlC set to allow long long\"" >&2;}
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_blacs}" ; then
 
@@ -10227,7 +10305,6 @@ echo "$as_me: WARNING: \"xlC set to allow long long\"" >&2;}
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${BLACS_LIB}"
 
    fi
-
 
 
    # set up lapack libraries
@@ -10830,7 +10907,6 @@ echo "$as_me: error: \"We do not support vendor mpi on the SUN yet!\"" >&2;}
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_gsl}"; then
 
@@ -10870,7 +10946,6 @@ echo "$as_me: error: \"We do not support vendor mpi on the SUN yet!\"" >&2;}
        VENDOR_INC_DIRS="${VENDOR_INC_DIRS} ${GSL_INC}"
 
    fi
-
 
 
 
@@ -10948,7 +11023,6 @@ echo "$as_me: error: \"We do not support vendor mpi on the SUN yet!\"" >&2;}
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${PCG_LIB}"
 
    fi
-
 
 
    # set up the libraries and include path
@@ -11033,7 +11107,6 @@ echo "$as_me: error: \"We do not support vendor mpi on the SUN yet!\"" >&2;}
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_blacs}" ; then
 
@@ -11068,7 +11141,6 @@ echo "$as_me: error: \"We do not support vendor mpi on the SUN yet!\"" >&2;}
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${BLACS_LIB}"
 
    fi
-
 
 
    # set up lapack libraries
@@ -11575,19 +11647,21 @@ echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
        fi
 
        # add vendors to rpath
-       for vendor_dir in ${VENDOR_LIB_DIRS};
-       do
-           if test "${dilem}" = "space"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "nospace"; then
-	       RPATH="${rptrigger}${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "colon"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           else
-               { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
+       for vendor_dir in ${VENDOR_LIB_DIRS}; do
+                      so_libs=`ls ${vendor_dir}/*.so 2>/dev/null`
+           if test ! "${so_libs:-none}" = "none"; then
+              if test "${dilem}" = "space"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "nospace"; then
+	          RPATH="${rptrigger}${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "colon"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              else
+                  { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
 echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
    { (exit 1); exit 1; }; }
-	   fi
+   	      fi
+           fi
        done
 
 
@@ -11945,7 +12019,6 @@ _ACEOF
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_gsl}"; then
 
@@ -11985,7 +12058,6 @@ _ACEOF
        VENDOR_INC_DIRS="${VENDOR_INC_DIRS} ${GSL_INC}"
 
    fi
-
 
 
 
@@ -12063,7 +12135,6 @@ _ACEOF
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${PCG_LIB}"
 
    fi
-
 
 
    # set up the libraries and include path
@@ -12148,7 +12219,6 @@ _ACEOF
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_blacs}" ; then
 
@@ -12183,7 +12253,6 @@ _ACEOF
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${BLACS_LIB}"
 
    fi
-
 
 
    # set up lapack libraries
@@ -13718,6 +13787,8 @@ s,@BIBTEX@,$BIBTEX,;t t
 s,@BIBTEXFLAGS@,$BIBTEXFLAGS,;t t
 s,@XDVI@,$XDVI,;t t
 s,@XDVIFLAGS@,$XDVIFLAGS,;t t
+s,@PS2PDF@,$PS2PDF,;t t
+s,@DOTCMD@,$DOTCMD,;t t
 s,@DVIPS@,$DVIPS,;t t
 s,@DVIPSFLAGS@,$DVIPSFLAGS,;t t
 s,@LP@,$LP,;t t
@@ -13786,8 +13857,6 @@ s,@rel_package_html@,$rel_package_html,;t t
 s,@header_dir@,$header_dir,;t t
 s,@autodoc_dir@,$autodoc_dir,;t t
 s,@FLEXELINT_PATH@,$FLEXELINT_PATH,;t t
-s,@DOTCMD@,$DOTCMD,;t t
-s,@PS2PDF@,$PS2PDF,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
diff --git a/src/fpe_trap/configure b/src/fpe_trap/configure
--- a/src/fpe_trap/configure
+++ b/src/fpe_trap/configure
@@ -271,7 +271,7 @@ PACKAGE_STRING=
 PACKAGE_BUGREPORT=
 
 ac_unique_file="Release.hh"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MPI_INC MPI_LIB latex_yes_no doxygen_output_top build build_cpu build_vendor build_os host host_cpu host_vendor host_os PYTHON_PATH PERL_PATH CVS_PATH GHOSTVIEW LATEX LATEXFLAGS BIBTEX BIBTEXFLAGS XDVI XDVIFLAGS DVIPS DVIPSFLAGS LP LPFLAGS DOXYGEN_PATH F90 F90FREE F90FIXED F90FLAGS MODFLAG CXX CC GCC_BIN RANLIB ac_ct_RANLIB CFLAGS CXXFLAGS LD LDFLAGS AR ARFLAGS CPPFLAGS DEPENDENCY_RULES STRICTFLAG PARALLEL_FLAG RPATH LIB_PREFIX INSTALL INSTALL_DATA installfiles install_executable install_lib install_headers installdirs alltarget libsuffix dirstoclean package DRACO_DEPENDS DRACO_LIBS VENDOR_DEPENDS VENDOR_INC VENDOR_LIBS ARLIBS PKG_DEPENDS PKG_LIBS DRACO_TEST_DEPENDS DRACO_TEST_LIBS VENDOR_TEST_DEPENDS VENDOR_TEST_LIBS ARTESTLIBS test_alltarget test_flags test_scalar test_nprocs test_output_files configure_command package_top_srcdir number doxygen_input doxygen_examples doxygen_html_output doxygen_latex_output DOXYGEN_TAGFILES rel_package_html header_dir autodoc_dir LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MPI_INC MPI_LIB latex_yes_no doxygen_output_top build build_cpu build_vendor build_os host host_cpu host_vendor host_os PYTHON_PATH PERL_PATH CVS_PATH GHOSTVIEW LATEX LATEXFLAGS BIBTEX BIBTEXFLAGS XDVI XDVIFLAGS PS2PDF DOTCMD DVIPS DVIPSFLAGS LP LPFLAGS DOXYGEN_PATH F90 F90FREE F90FIXED F90FLAGS MODFLAG CXX CC GCC_BIN RANLIB ac_ct_RANLIB CFLAGS CXXFLAGS LD LDFLAGS AR ARFLAGS CPPFLAGS DEPENDENCY_RULES STRICTFLAG PARALLEL_FLAG RPATH LIB_PREFIX INSTALL INSTALL_DATA installfiles install_executable install_lib install_headers installdirs alltarget libsuffix dirstoclean package DRACO_DEPENDS DRACO_LIBS VENDOR_DEPENDS VENDOR_INC VENDOR_LIBS ARLIBS PKG_DEPENDS PKG_LIBS DRACO_TEST_DEPENDS DRACO_TEST_LIBS VENDOR_TEST_DEPENDS VENDOR_TEST_LIBS ARTESTLIBS test_alltarget test_flags test_scalar test_nprocs test_output_files configure_command package_top_srcdir number doxygen_input doxygen_examples doxygen_html_output doxygen_latex_output DOXYGEN_TAGFILES rel_package_html header_dir autodoc_dir LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -2148,6 +2148,98 @@ test -n "$XDVI" || XDVI="null"
 echo "$as_me: WARNING: \"No valid xdvi found!\"" >&2;}
    fi
 
+
+      for ac_prog in ps2pdf
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_PS2PDF+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$PS2PDF"; then
+  ac_cv_prog_PS2PDF="$PS2PDF" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_PS2PDF="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+PS2PDF=$ac_cv_prog_PS2PDF
+if test -n "$PS2PDF"; then
+  echo "$as_me:$LINENO: result: $PS2PDF" >&5
+echo "${ECHO_T}$PS2PDF" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$PS2PDF" && break
+done
+test -n "$PS2PDF" || PS2PDF="null"
+
+   if test "${PS2PDF}" = null ; then
+       { echo "$as_me:$LINENO: WARNING: \"No valid ps2pdf found!\"" >&5
+echo "$as_me: WARNING: \"No valid ps2pdf found!\"" >&2;}
+   fi
+
+      for ac_prog in dot
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_DOTCMD+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$DOTCMD"; then
+  ac_cv_prog_DOTCMD="$DOTCMD" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_DOTCMD="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+DOTCMD=$ac_cv_prog_DOTCMD
+if test -n "$DOTCMD"; then
+  echo "$as_me:$LINENO: result: $DOTCMD" >&5
+echo "${ECHO_T}$DOTCMD" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$DOTCMD" && break
+done
+test -n "$DOTCMD" || DOTCMD="null"
+
+   if test "${DOTCMD}" = null ; then
+       { echo "$as_me:$LINENO: WARNING: \"No valid dot found!\"" >&5
+echo "$as_me: WARNING: \"No valid dot found!\"" >&2;}
+   fi
 
       for ac_prog in dvips
 do
@@ -6094,7 +6186,6 @@ _ACEOF
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_gsl}"; then
 
@@ -6134,7 +6225,6 @@ _ACEOF
        VENDOR_INC_DIRS="${VENDOR_INC_DIRS} ${GSL_INC}"
 
    fi
-
 
 
 
@@ -6212,7 +6302,6 @@ _ACEOF
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${PCG_LIB}"
 
    fi
-
 
 
    # set up the libraries and include path
@@ -6297,7 +6386,6 @@ _ACEOF
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_blacs}" ; then
 
@@ -6332,7 +6420,6 @@ _ACEOF
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${BLACS_LIB}"
 
    fi
-
 
 
    # set up lapack libraries
@@ -6842,19 +6929,21 @@ echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
        fi
 
        # add vendors to rpath
-       for vendor_dir in ${VENDOR_LIB_DIRS};
-       do
-           if test "${dilem}" = "space"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "nospace"; then
-	       RPATH="${rptrigger}${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "colon"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           else
-               { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
+       for vendor_dir in ${VENDOR_LIB_DIRS}; do
+                      so_libs=`ls ${vendor_dir}/*.so 2>/dev/null`
+           if test ! "${so_libs:-none}" = "none"; then
+              if test "${dilem}" = "space"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "nospace"; then
+	          RPATH="${rptrigger}${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "colon"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              else
+                  { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
 echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
    { (exit 1); exit 1; }; }
-	   fi
+   	      fi
+           fi
        done
 
 
@@ -6889,19 +6978,21 @@ echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
        fi
 
        # add vendors to rpath
-       for vendor_dir in ${VENDOR_LIB_DIRS};
-       do
-           if test "${dilem}" = "space"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "nospace"; then
-	       RPATH="${rptrigger}${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "colon"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           else
-               { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
+       for vendor_dir in ${VENDOR_LIB_DIRS}; do
+                      so_libs=`ls ${vendor_dir}/*.so 2>/dev/null`
+           if test ! "${so_libs:-none}" = "none"; then
+              if test "${dilem}" = "space"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "nospace"; then
+	          RPATH="${rptrigger}${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "colon"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              else
+                  { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
 echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
    { (exit 1); exit 1; }; }
-	   fi
+   	      fi
+           fi
        done
 
 
@@ -7118,7 +7209,6 @@ echo "${ECHO_T}\"not needed\"" >&6
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_gsl}"; then
 
@@ -7158,7 +7248,6 @@ echo "${ECHO_T}\"not needed\"" >&6
        VENDOR_INC_DIRS="${VENDOR_INC_DIRS} ${GSL_INC}"
 
    fi
-
 
 
 
@@ -7236,7 +7325,6 @@ echo "${ECHO_T}\"not needed\"" >&6
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${PCG_LIB}"
 
    fi
-
 
 
    # set up the libraries and include path
@@ -7321,7 +7409,6 @@ echo "${ECHO_T}\"not needed\"" >&6
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_blacs}" ; then
 
@@ -7356,7 +7443,6 @@ echo "${ECHO_T}\"not needed\"" >&6
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${BLACS_LIB}"
 
    fi
-
 
 
    # set up lapack libraries
@@ -7863,19 +7949,21 @@ echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
        fi
 
        # add vendors to rpath
-       for vendor_dir in ${VENDOR_LIB_DIRS};
-       do
-           if test "${dilem}" = "space"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "nospace"; then
-	       RPATH="${rptrigger}${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "colon"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           else
-               { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
+       for vendor_dir in ${VENDOR_LIB_DIRS}; do
+                      so_libs=`ls ${vendor_dir}/*.so 2>/dev/null`
+           if test ! "${so_libs:-none}" = "none"; then
+              if test "${dilem}" = "space"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "nospace"; then
+	          RPATH="${rptrigger}${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "colon"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              else
+                  { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
 echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
    { (exit 1); exit 1; }; }
-	   fi
+   	      fi
+           fi
        done
 
 
@@ -8116,7 +8204,6 @@ echo "${ECHO_T}\"not needed\"" >&6
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_gsl}"; then
 
@@ -8156,7 +8243,6 @@ echo "${ECHO_T}\"not needed\"" >&6
        VENDOR_INC_DIRS="${VENDOR_INC_DIRS} ${GSL_INC}"
 
    fi
-
 
 
 
@@ -8234,7 +8320,6 @@ echo "${ECHO_T}\"not needed\"" >&6
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${PCG_LIB}"
 
    fi
-
 
 
    # set up the libraries and include path
@@ -8319,7 +8404,6 @@ echo "${ECHO_T}\"not needed\"" >&6
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_blacs}" ; then
 
@@ -8354,7 +8438,6 @@ echo "${ECHO_T}\"not needed\"" >&6
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${BLACS_LIB}"
 
    fi
-
 
 
    # set up lapack libraries
@@ -8861,19 +8944,21 @@ echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
        fi
 
        # add vendors to rpath
-       for vendor_dir in ${VENDOR_LIB_DIRS};
-       do
-           if test "${dilem}" = "space"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "nospace"; then
-	       RPATH="${rptrigger}${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "colon"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           else
-               { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
+       for vendor_dir in ${VENDOR_LIB_DIRS}; do
+                      so_libs=`ls ${vendor_dir}/*.so 2>/dev/null`
+           if test ! "${so_libs:-none}" = "none"; then
+              if test "${dilem}" = "space"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "nospace"; then
+	          RPATH="${rptrigger}${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "colon"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              else
+                  { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
 echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
    { (exit 1); exit 1; }; }
-	   fi
+   	      fi
+           fi
        done
 
 
@@ -9169,7 +9254,6 @@ _ACEOF
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_gsl}"; then
 
@@ -9209,7 +9293,6 @@ _ACEOF
        VENDOR_INC_DIRS="${VENDOR_INC_DIRS} ${GSL_INC}"
 
    fi
-
 
 
 
@@ -9287,7 +9370,6 @@ _ACEOF
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${PCG_LIB}"
 
    fi
-
 
 
    # set up the libraries and include path
@@ -9372,7 +9454,6 @@ _ACEOF
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_blacs}" ; then
 
@@ -9407,7 +9488,6 @@ _ACEOF
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${BLACS_LIB}"
 
    fi
-
 
 
    # set up lapack libraries
@@ -9914,19 +9994,21 @@ echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
        fi
 
        # add vendors to rpath
-       for vendor_dir in ${VENDOR_LIB_DIRS};
-       do
-           if test "${dilem}" = "space"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "nospace"; then
-	       RPATH="${rptrigger}${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "colon"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           else
-               { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
+       for vendor_dir in ${VENDOR_LIB_DIRS}; do
+                      so_libs=`ls ${vendor_dir}/*.so 2>/dev/null`
+           if test ! "${so_libs:-none}" = "none"; then
+              if test "${dilem}" = "space"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "nospace"; then
+	          RPATH="${rptrigger}${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "colon"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              else
+                  { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
 echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
    { (exit 1); exit 1; }; }
-	   fi
+   	      fi
+           fi
        done
 
 
@@ -10137,7 +10219,6 @@ echo "$as_me: WARNING: \"xlC set to allow long long\"" >&2;}
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_gsl}"; then
 
@@ -10177,7 +10258,6 @@ echo "$as_me: WARNING: \"xlC set to allow long long\"" >&2;}
        VENDOR_INC_DIRS="${VENDOR_INC_DIRS} ${GSL_INC}"
 
    fi
-
 
 
 
@@ -10255,7 +10335,6 @@ echo "$as_me: WARNING: \"xlC set to allow long long\"" >&2;}
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${PCG_LIB}"
 
    fi
-
 
 
    # set up the libraries and include path
@@ -10340,7 +10419,6 @@ echo "$as_me: WARNING: \"xlC set to allow long long\"" >&2;}
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_blacs}" ; then
 
@@ -10375,7 +10453,6 @@ echo "$as_me: WARNING: \"xlC set to allow long long\"" >&2;}
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${BLACS_LIB}"
 
    fi
-
 
 
    # set up lapack libraries
@@ -10978,7 +11055,6 @@ echo "$as_me: error: \"We do not support vendor mpi on the SUN yet!\"" >&2;}
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_gsl}"; then
 
@@ -11018,7 +11094,6 @@ echo "$as_me: error: \"We do not support vendor mpi on the SUN yet!\"" >&2;}
        VENDOR_INC_DIRS="${VENDOR_INC_DIRS} ${GSL_INC}"
 
    fi
-
 
 
 
@@ -11096,7 +11171,6 @@ echo "$as_me: error: \"We do not support vendor mpi on the SUN yet!\"" >&2;}
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${PCG_LIB}"
 
    fi
-
 
 
    # set up the libraries and include path
@@ -11181,7 +11255,6 @@ echo "$as_me: error: \"We do not support vendor mpi on the SUN yet!\"" >&2;}
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_blacs}" ; then
 
@@ -11216,7 +11289,6 @@ echo "$as_me: error: \"We do not support vendor mpi on the SUN yet!\"" >&2;}
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${BLACS_LIB}"
 
    fi
-
 
 
    # set up lapack libraries
@@ -11723,19 +11795,21 @@ echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
        fi
 
        # add vendors to rpath
-       for vendor_dir in ${VENDOR_LIB_DIRS};
-       do
-           if test "${dilem}" = "space"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "nospace"; then
-	       RPATH="${rptrigger}${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "colon"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           else
-               { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
+       for vendor_dir in ${VENDOR_LIB_DIRS}; do
+                      so_libs=`ls ${vendor_dir}/*.so 2>/dev/null`
+           if test ! "${so_libs:-none}" = "none"; then
+              if test "${dilem}" = "space"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "nospace"; then
+	          RPATH="${rptrigger}${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "colon"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              else
+                  { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
 echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
    { (exit 1); exit 1; }; }
-	   fi
+   	      fi
+           fi
        done
 
 
@@ -12093,7 +12167,6 @@ _ACEOF
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_gsl}"; then
 
@@ -12133,7 +12206,6 @@ _ACEOF
        VENDOR_INC_DIRS="${VENDOR_INC_DIRS} ${GSL_INC}"
 
    fi
-
 
 
 
@@ -12211,7 +12283,6 @@ _ACEOF
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${PCG_LIB}"
 
    fi
-
 
 
    # set up the libraries and include path
@@ -12296,7 +12367,6 @@ _ACEOF
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_blacs}" ; then
 
@@ -12331,7 +12401,6 @@ _ACEOF
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${BLACS_LIB}"
 
    fi
-
 
 
    # set up lapack libraries
@@ -13775,6 +13844,8 @@ s,@BIBTEX@,$BIBTEX,;t t
 s,@BIBTEXFLAGS@,$BIBTEXFLAGS,;t t
 s,@XDVI@,$XDVI,;t t
 s,@XDVIFLAGS@,$XDVIFLAGS,;t t
+s,@PS2PDF@,$PS2PDF,;t t
+s,@DOTCMD@,$DOTCMD,;t t
 s,@DVIPS@,$DVIPS,;t t
 s,@DVIPSFLAGS@,$DVIPSFLAGS,;t t
 s,@LP@,$LP,;t t
diff --git a/src/mesh_element/configure b/src/mesh_element/configure
--- a/src/mesh_element/configure
+++ b/src/mesh_element/configure
@@ -271,7 +271,7 @@ PACKAGE_STRING=
 PACKAGE_BUGREPORT=
 
 ac_unique_file="Release.hh"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS latex_yes_no doxygen_output_top build build_cpu build_vendor build_os host host_cpu host_vendor host_os PYTHON_PATH PERL_PATH CVS_PATH GHOSTVIEW LATEX LATEXFLAGS BIBTEX BIBTEXFLAGS XDVI XDVIFLAGS DVIPS DVIPSFLAGS LP LPFLAGS DOXYGEN_PATH F90 F90FREE F90FIXED F90FLAGS MODFLAG CXX CC GCC_BIN RANLIB ac_ct_RANLIB CFLAGS CXXFLAGS LD LDFLAGS AR ARFLAGS CPPFLAGS DEPENDENCY_RULES STRICTFLAG PARALLEL_FLAG RPATH LIB_PREFIX INSTALL INSTALL_DATA installfiles install_executable install_lib install_headers installdirs alltarget libsuffix dirstoclean package DRACO_DEPENDS DRACO_LIBS VENDOR_DEPENDS VENDOR_INC VENDOR_LIBS ARLIBS PKG_DEPENDS PKG_LIBS DRACO_TEST_DEPENDS DRACO_TEST_LIBS VENDOR_TEST_DEPENDS VENDOR_TEST_LIBS ARTESTLIBS test_alltarget test_flags test_scalar test_nprocs test_output_files configure_command package_top_srcdir number doxygen_input doxygen_examples doxygen_html_output doxygen_latex_output DOXYGEN_TAGFILES rel_package_html header_dir autodoc_dir LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS latex_yes_no doxygen_output_top build build_cpu build_vendor build_os host host_cpu host_vendor host_os PYTHON_PATH PERL_PATH CVS_PATH GHOSTVIEW LATEX LATEXFLAGS BIBTEX BIBTEXFLAGS XDVI XDVIFLAGS PS2PDF DOTCMD DVIPS DVIPSFLAGS LP LPFLAGS DOXYGEN_PATH F90 F90FREE F90FIXED F90FLAGS MODFLAG CXX CC GCC_BIN RANLIB ac_ct_RANLIB CFLAGS CXXFLAGS LD LDFLAGS AR ARFLAGS CPPFLAGS DEPENDENCY_RULES STRICTFLAG PARALLEL_FLAG RPATH LIB_PREFIX INSTALL INSTALL_DATA installfiles install_executable install_lib install_headers installdirs alltarget libsuffix dirstoclean package DRACO_DEPENDS DRACO_LIBS VENDOR_DEPENDS VENDOR_INC VENDOR_LIBS ARLIBS PKG_DEPENDS PKG_LIBS DRACO_TEST_DEPENDS DRACO_TEST_LIBS VENDOR_TEST_DEPENDS VENDOR_TEST_LIBS ARTESTLIBS test_alltarget test_flags test_scalar test_nprocs test_output_files configure_command package_top_srcdir number doxygen_input doxygen_examples doxygen_html_output doxygen_latex_output DOXYGEN_TAGFILES rel_package_html header_dir autodoc_dir LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -2018,6 +2018,98 @@ test -n "$XDVI" || XDVI="null"
 echo "$as_me: WARNING: \"No valid xdvi found!\"" >&2;}
    fi
 
+
+      for ac_prog in ps2pdf
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_PS2PDF+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$PS2PDF"; then
+  ac_cv_prog_PS2PDF="$PS2PDF" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_PS2PDF="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+PS2PDF=$ac_cv_prog_PS2PDF
+if test -n "$PS2PDF"; then
+  echo "$as_me:$LINENO: result: $PS2PDF" >&5
+echo "${ECHO_T}$PS2PDF" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$PS2PDF" && break
+done
+test -n "$PS2PDF" || PS2PDF="null"
+
+   if test "${PS2PDF}" = null ; then
+       { echo "$as_me:$LINENO: WARNING: \"No valid ps2pdf found!\"" >&5
+echo "$as_me: WARNING: \"No valid ps2pdf found!\"" >&2;}
+   fi
+
+      for ac_prog in dot
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_DOTCMD+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$DOTCMD"; then
+  ac_cv_prog_DOTCMD="$DOTCMD" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_DOTCMD="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+DOTCMD=$ac_cv_prog_DOTCMD
+if test -n "$DOTCMD"; then
+  echo "$as_me:$LINENO: result: $DOTCMD" >&5
+echo "${ECHO_T}$DOTCMD" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$DOTCMD" && break
+done
+test -n "$DOTCMD" || DOTCMD="null"
+
+   if test "${DOTCMD}" = null ; then
+       { echo "$as_me:$LINENO: WARNING: \"No valid dot found!\"" >&5
+echo "$as_me: WARNING: \"No valid dot found!\"" >&2;}
+   fi
 
       for ac_prog in dvips
 do
@@ -5964,7 +6056,6 @@ _ACEOF
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_gsl}"; then
 
@@ -6004,7 +6095,6 @@ _ACEOF
        VENDOR_INC_DIRS="${VENDOR_INC_DIRS} ${GSL_INC}"
 
    fi
-
 
 
 
@@ -6082,7 +6172,6 @@ _ACEOF
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${PCG_LIB}"
 
    fi
-
 
 
    # set up the libraries and include path
@@ -6167,7 +6256,6 @@ _ACEOF
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_blacs}" ; then
 
@@ -6202,7 +6290,6 @@ _ACEOF
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${BLACS_LIB}"
 
    fi
-
 
 
    # set up lapack libraries
@@ -6712,19 +6799,21 @@ echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
        fi
 
        # add vendors to rpath
-       for vendor_dir in ${VENDOR_LIB_DIRS};
-       do
-           if test "${dilem}" = "space"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "nospace"; then
-	       RPATH="${rptrigger}${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "colon"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           else
-               { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
+       for vendor_dir in ${VENDOR_LIB_DIRS}; do
+                      so_libs=`ls ${vendor_dir}/*.so 2>/dev/null`
+           if test ! "${so_libs:-none}" = "none"; then
+              if test "${dilem}" = "space"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "nospace"; then
+	          RPATH="${rptrigger}${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "colon"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              else
+                  { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
 echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
    { (exit 1); exit 1; }; }
-	   fi
+   	      fi
+           fi
        done
 
 
@@ -6759,19 +6848,21 @@ echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
        fi
 
        # add vendors to rpath
-       for vendor_dir in ${VENDOR_LIB_DIRS};
-       do
-           if test "${dilem}" = "space"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "nospace"; then
-	       RPATH="${rptrigger}${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "colon"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           else
-               { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
+       for vendor_dir in ${VENDOR_LIB_DIRS}; do
+                      so_libs=`ls ${vendor_dir}/*.so 2>/dev/null`
+           if test ! "${so_libs:-none}" = "none"; then
+              if test "${dilem}" = "space"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "nospace"; then
+	          RPATH="${rptrigger}${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "colon"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              else
+                  { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
 echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
    { (exit 1); exit 1; }; }
-	   fi
+   	      fi
+           fi
        done
 
 
@@ -6988,7 +7079,6 @@ echo "${ECHO_T}\"not needed\"" >&6
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_gsl}"; then
 
@@ -7028,7 +7118,6 @@ echo "${ECHO_T}\"not needed\"" >&6
        VENDOR_INC_DIRS="${VENDOR_INC_DIRS} ${GSL_INC}"
 
    fi
-
 
 
 
@@ -7106,7 +7195,6 @@ echo "${ECHO_T}\"not needed\"" >&6
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${PCG_LIB}"
 
    fi
-
 
 
    # set up the libraries and include path
@@ -7191,7 +7279,6 @@ echo "${ECHO_T}\"not needed\"" >&6
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_blacs}" ; then
 
@@ -7226,7 +7313,6 @@ echo "${ECHO_T}\"not needed\"" >&6
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${BLACS_LIB}"
 
    fi
-
 
 
    # set up lapack libraries
@@ -7733,19 +7819,21 @@ echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
        fi
 
        # add vendors to rpath
-       for vendor_dir in ${VENDOR_LIB_DIRS};
-       do
-           if test "${dilem}" = "space"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "nospace"; then
-	       RPATH="${rptrigger}${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "colon"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           else
-               { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
+       for vendor_dir in ${VENDOR_LIB_DIRS}; do
+                      so_libs=`ls ${vendor_dir}/*.so 2>/dev/null`
+           if test ! "${so_libs:-none}" = "none"; then
+              if test "${dilem}" = "space"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "nospace"; then
+	          RPATH="${rptrigger}${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "colon"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              else
+                  { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
 echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
    { (exit 1); exit 1; }; }
-	   fi
+   	      fi
+           fi
        done
 
 
@@ -7986,7 +8074,6 @@ echo "${ECHO_T}\"not needed\"" >&6
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_gsl}"; then
 
@@ -8026,7 +8113,6 @@ echo "${ECHO_T}\"not needed\"" >&6
        VENDOR_INC_DIRS="${VENDOR_INC_DIRS} ${GSL_INC}"
 
    fi
-
 
 
 
@@ -8104,7 +8190,6 @@ echo "${ECHO_T}\"not needed\"" >&6
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${PCG_LIB}"
 
    fi
-
 
 
    # set up the libraries and include path
@@ -8189,7 +8274,6 @@ echo "${ECHO_T}\"not needed\"" >&6
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_blacs}" ; then
 
@@ -8224,7 +8308,6 @@ echo "${ECHO_T}\"not needed\"" >&6
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${BLACS_LIB}"
 
    fi
-
 
 
    # set up lapack libraries
@@ -8731,19 +8814,21 @@ echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
        fi
 
        # add vendors to rpath
-       for vendor_dir in ${VENDOR_LIB_DIRS};
-       do
-           if test "${dilem}" = "space"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "nospace"; then
-	       RPATH="${rptrigger}${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "colon"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           else
-               { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
+       for vendor_dir in ${VENDOR_LIB_DIRS}; do
+                      so_libs=`ls ${vendor_dir}/*.so 2>/dev/null`
+           if test ! "${so_libs:-none}" = "none"; then
+              if test "${dilem}" = "space"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "nospace"; then
+	          RPATH="${rptrigger}${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "colon"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              else
+                  { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
 echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
    { (exit 1); exit 1; }; }
-	   fi
+   	      fi
+           fi
        done
 
 
@@ -9039,7 +9124,6 @@ _ACEOF
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_gsl}"; then
 
@@ -9079,7 +9163,6 @@ _ACEOF
        VENDOR_INC_DIRS="${VENDOR_INC_DIRS} ${GSL_INC}"
 
    fi
-
 
 
 
@@ -9157,7 +9240,6 @@ _ACEOF
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${PCG_LIB}"
 
    fi
-
 
 
    # set up the libraries and include path
@@ -9242,7 +9324,6 @@ _ACEOF
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_blacs}" ; then
 
@@ -9277,7 +9358,6 @@ _ACEOF
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${BLACS_LIB}"
 
    fi
-
 
 
    # set up lapack libraries
@@ -9784,19 +9864,21 @@ echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
        fi
 
        # add vendors to rpath
-       for vendor_dir in ${VENDOR_LIB_DIRS};
-       do
-           if test "${dilem}" = "space"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "nospace"; then
-	       RPATH="${rptrigger}${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "colon"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           else
-               { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
+       for vendor_dir in ${VENDOR_LIB_DIRS}; do
+                      so_libs=`ls ${vendor_dir}/*.so 2>/dev/null`
+           if test ! "${so_libs:-none}" = "none"; then
+              if test "${dilem}" = "space"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "nospace"; then
+	          RPATH="${rptrigger}${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "colon"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              else
+                  { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
 echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
    { (exit 1); exit 1; }; }
-	   fi
+   	      fi
+           fi
        done
 
 
@@ -10007,7 +10089,6 @@ echo "$as_me: WARNING: \"xlC set to allow long long\"" >&2;}
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_gsl}"; then
 
@@ -10047,7 +10128,6 @@ echo "$as_me: WARNING: \"xlC set to allow long long\"" >&2;}
        VENDOR_INC_DIRS="${VENDOR_INC_DIRS} ${GSL_INC}"
 
    fi
-
 
 
 
@@ -10125,7 +10205,6 @@ echo "$as_me: WARNING: \"xlC set to allow long long\"" >&2;}
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${PCG_LIB}"
 
    fi
-
 
 
    # set up the libraries and include path
@@ -10210,7 +10289,6 @@ echo "$as_me: WARNING: \"xlC set to allow long long\"" >&2;}
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_blacs}" ; then
 
@@ -10245,7 +10323,6 @@ echo "$as_me: WARNING: \"xlC set to allow long long\"" >&2;}
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${BLACS_LIB}"
 
    fi
-
 
 
    # set up lapack libraries
@@ -10848,7 +10925,6 @@ echo "$as_me: error: \"We do not support vendor mpi on the SUN yet!\"" >&2;}
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_gsl}"; then
 
@@ -10888,7 +10964,6 @@ echo "$as_me: error: \"We do not support vendor mpi on the SUN yet!\"" >&2;}
        VENDOR_INC_DIRS="${VENDOR_INC_DIRS} ${GSL_INC}"
 
    fi
-
 
 
 
@@ -10966,7 +11041,6 @@ echo "$as_me: error: \"We do not support vendor mpi on the SUN yet!\"" >&2;}
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${PCG_LIB}"
 
    fi
-
 
 
    # set up the libraries and include path
@@ -11051,7 +11125,6 @@ echo "$as_me: error: \"We do not support vendor mpi on the SUN yet!\"" >&2;}
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_blacs}" ; then
 
@@ -11086,7 +11159,6 @@ echo "$as_me: error: \"We do not support vendor mpi on the SUN yet!\"" >&2;}
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${BLACS_LIB}"
 
    fi
-
 
 
    # set up lapack libraries
@@ -11593,19 +11665,21 @@ echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
        fi
 
        # add vendors to rpath
-       for vendor_dir in ${VENDOR_LIB_DIRS};
-       do
-           if test "${dilem}" = "space"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "nospace"; then
-	       RPATH="${rptrigger}${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "colon"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           else
-               { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
+       for vendor_dir in ${VENDOR_LIB_DIRS}; do
+                      so_libs=`ls ${vendor_dir}/*.so 2>/dev/null`
+           if test ! "${so_libs:-none}" = "none"; then
+              if test "${dilem}" = "space"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "nospace"; then
+	          RPATH="${rptrigger}${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "colon"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              else
+                  { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
 echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
    { (exit 1); exit 1; }; }
-	   fi
+   	      fi
+           fi
        done
 
 
@@ -11963,7 +12037,6 @@ _ACEOF
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_gsl}"; then
 
@@ -12003,7 +12076,6 @@ _ACEOF
        VENDOR_INC_DIRS="${VENDOR_INC_DIRS} ${GSL_INC}"
 
    fi
-
 
 
 
@@ -12081,7 +12153,6 @@ _ACEOF
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${PCG_LIB}"
 
    fi
-
 
 
    # set up the libraries and include path
@@ -12166,7 +12237,6 @@ _ACEOF
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_blacs}" ; then
 
@@ -12201,7 +12271,6 @@ _ACEOF
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${BLACS_LIB}"
 
    fi
-
 
 
    # set up lapack libraries
@@ -13614,6 +13683,8 @@ s,@BIBTEX@,$BIBTEX,;t t
 s,@BIBTEXFLAGS@,$BIBTEXFLAGS,;t t
 s,@XDVI@,$XDVI,;t t
 s,@XDVIFLAGS@,$XDVIFLAGS,;t t
+s,@PS2PDF@,$PS2PDF,;t t
+s,@DOTCMD@,$DOTCMD,;t t
 s,@DVIPS@,$DVIPS,;t t
 s,@DVIPSFLAGS@,$DVIPSFLAGS,;t t
 s,@LP@,$LP,;t t
diff --git a/src/shared_lib/configure b/src/shared_lib/configure
--- a/src/shared_lib/configure
+++ b/src/shared_lib/configure
@@ -271,7 +271,7 @@ PACKAGE_STRING=
 PACKAGE_BUGREPORT=
 
 ac_unique_file="Shared_Lib.hh"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS latex_yes_no doxygen_output_top build build_cpu build_vendor build_os host host_cpu host_vendor host_os PYTHON_PATH PERL_PATH CVS_PATH GHOSTVIEW LATEX LATEXFLAGS BIBTEX BIBTEXFLAGS XDVI XDVIFLAGS DVIPS DVIPSFLAGS LP LPFLAGS DOXYGEN_PATH F90 F90FREE F90FIXED F90FLAGS MODFLAG CXX CC GCC_BIN RANLIB ac_ct_RANLIB CFLAGS CXXFLAGS LD LDFLAGS AR ARFLAGS CPPFLAGS DEPENDENCY_RULES STRICTFLAG PARALLEL_FLAG RPATH LIB_PREFIX INSTALL INSTALL_DATA installfiles install_executable install_lib install_headers installdirs alltarget libsuffix dirstoclean package DRACO_DEPENDS DRACO_LIBS VENDOR_DEPENDS VENDOR_INC VENDOR_LIBS ARLIBS PKG_DEPENDS PKG_LIBS DRACO_TEST_DEPENDS DRACO_TEST_LIBS VENDOR_TEST_DEPENDS VENDOR_TEST_LIBS ARTESTLIBS test_alltarget test_flags test_scalar test_nprocs test_output_files configure_command package_top_srcdir number doxygen_input doxygen_examples doxygen_html_output doxygen_latex_output DOXYGEN_TAGFILES rel_package_html header_dir autodoc_dir LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS latex_yes_no doxygen_output_top build build_cpu build_vendor build_os host host_cpu host_vendor host_os PYTHON_PATH PERL_PATH CVS_PATH GHOSTVIEW LATEX LATEXFLAGS BIBTEX BIBTEXFLAGS XDVI XDVIFLAGS PS2PDF DOTCMD DVIPS DVIPSFLAGS LP LPFLAGS DOXYGEN_PATH F90 F90FREE F90FIXED F90FLAGS MODFLAG CXX CC GCC_BIN RANLIB ac_ct_RANLIB CFLAGS CXXFLAGS LD LDFLAGS AR ARFLAGS CPPFLAGS DEPENDENCY_RULES STRICTFLAG PARALLEL_FLAG RPATH LIB_PREFIX INSTALL INSTALL_DATA installfiles install_executable install_lib install_headers installdirs alltarget libsuffix dirstoclean package DRACO_DEPENDS DRACO_LIBS VENDOR_DEPENDS VENDOR_INC VENDOR_LIBS ARLIBS PKG_DEPENDS PKG_LIBS DRACO_TEST_DEPENDS DRACO_TEST_LIBS VENDOR_TEST_DEPENDS VENDOR_TEST_LIBS ARTESTLIBS test_alltarget test_flags test_scalar test_nprocs test_output_files configure_command package_top_srcdir number doxygen_input doxygen_examples doxygen_html_output doxygen_latex_output DOXYGEN_TAGFILES rel_package_html header_dir autodoc_dir LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -2059,6 +2059,98 @@ test -n "$XDVI" || XDVI="null"
 echo "$as_me: WARNING: \"No valid xdvi found!\"" >&2;}
    fi
 
+
+      for ac_prog in ps2pdf
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_PS2PDF+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$PS2PDF"; then
+  ac_cv_prog_PS2PDF="$PS2PDF" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_PS2PDF="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+PS2PDF=$ac_cv_prog_PS2PDF
+if test -n "$PS2PDF"; then
+  echo "$as_me:$LINENO: result: $PS2PDF" >&5
+echo "${ECHO_T}$PS2PDF" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$PS2PDF" && break
+done
+test -n "$PS2PDF" || PS2PDF="null"
+
+   if test "${PS2PDF}" = null ; then
+       { echo "$as_me:$LINENO: WARNING: \"No valid ps2pdf found!\"" >&5
+echo "$as_me: WARNING: \"No valid ps2pdf found!\"" >&2;}
+   fi
+
+      for ac_prog in dot
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_DOTCMD+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$DOTCMD"; then
+  ac_cv_prog_DOTCMD="$DOTCMD" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_DOTCMD="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+DOTCMD=$ac_cv_prog_DOTCMD
+if test -n "$DOTCMD"; then
+  echo "$as_me:$LINENO: result: $DOTCMD" >&5
+echo "${ECHO_T}$DOTCMD" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$DOTCMD" && break
+done
+test -n "$DOTCMD" || DOTCMD="null"
+
+   if test "${DOTCMD}" = null ; then
+       { echo "$as_me:$LINENO: WARNING: \"No valid dot found!\"" >&5
+echo "$as_me: WARNING: \"No valid dot found!\"" >&2;}
+   fi
 
       for ac_prog in dvips
 do
@@ -6005,7 +6097,6 @@ _ACEOF
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_gsl}"; then
 
@@ -6045,7 +6136,6 @@ _ACEOF
        VENDOR_INC_DIRS="${VENDOR_INC_DIRS} ${GSL_INC}"
 
    fi
-
 
 
 
@@ -6123,7 +6213,6 @@ _ACEOF
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${PCG_LIB}"
 
    fi
-
 
 
    # set up the libraries and include path
@@ -6208,7 +6297,6 @@ _ACEOF
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_blacs}" ; then
 
@@ -6243,7 +6331,6 @@ _ACEOF
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${BLACS_LIB}"
 
    fi
-
 
 
    # set up lapack libraries
@@ -6753,19 +6840,21 @@ echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
        fi
 
        # add vendors to rpath
-       for vendor_dir in ${VENDOR_LIB_DIRS};
-       do
-           if test "${dilem}" = "space"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "nospace"; then
-	       RPATH="${rptrigger}${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "colon"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           else
-               { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
+       for vendor_dir in ${VENDOR_LIB_DIRS}; do
+                      so_libs=`ls ${vendor_dir}/*.so 2>/dev/null`
+           if test ! "${so_libs:-none}" = "none"; then
+              if test "${dilem}" = "space"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "nospace"; then
+	          RPATH="${rptrigger}${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "colon"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              else
+                  { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
 echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
    { (exit 1); exit 1; }; }
-	   fi
+   	      fi
+           fi
        done
 
 
@@ -6800,19 +6889,21 @@ echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
        fi
 
        # add vendors to rpath
-       for vendor_dir in ${VENDOR_LIB_DIRS};
-       do
-           if test "${dilem}" = "space"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "nospace"; then
-	       RPATH="${rptrigger}${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "colon"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           else
-               { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
+       for vendor_dir in ${VENDOR_LIB_DIRS}; do
+                      so_libs=`ls ${vendor_dir}/*.so 2>/dev/null`
+           if test ! "${so_libs:-none}" = "none"; then
+              if test "${dilem}" = "space"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "nospace"; then
+	          RPATH="${rptrigger}${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "colon"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              else
+                  { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
 echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
    { (exit 1); exit 1; }; }
-	   fi
+   	      fi
+           fi
        done
 
 
@@ -7029,7 +7120,6 @@ echo "${ECHO_T}\"not needed\"" >&6
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_gsl}"; then
 
@@ -7069,7 +7159,6 @@ echo "${ECHO_T}\"not needed\"" >&6
        VENDOR_INC_DIRS="${VENDOR_INC_DIRS} ${GSL_INC}"
 
    fi
-
 
 
 
@@ -7147,7 +7236,6 @@ echo "${ECHO_T}\"not needed\"" >&6
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${PCG_LIB}"
 
    fi
-
 
 
    # set up the libraries and include path
@@ -7232,7 +7320,6 @@ echo "${ECHO_T}\"not needed\"" >&6
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_blacs}" ; then
 
@@ -7267,7 +7354,6 @@ echo "${ECHO_T}\"not needed\"" >&6
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${BLACS_LIB}"
 
    fi
-
 
 
    # set up lapack libraries
@@ -7774,19 +7860,21 @@ echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
        fi
 
        # add vendors to rpath
-       for vendor_dir in ${VENDOR_LIB_DIRS};
-       do
-           if test "${dilem}" = "space"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "nospace"; then
-	       RPATH="${rptrigger}${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "colon"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           else
-               { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
+       for vendor_dir in ${VENDOR_LIB_DIRS}; do
+                      so_libs=`ls ${vendor_dir}/*.so 2>/dev/null`
+           if test ! "${so_libs:-none}" = "none"; then
+              if test "${dilem}" = "space"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "nospace"; then
+	          RPATH="${rptrigger}${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "colon"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              else
+                  { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
 echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
    { (exit 1); exit 1; }; }
-	   fi
+   	      fi
+           fi
        done
 
 
@@ -8027,7 +8115,6 @@ echo "${ECHO_T}\"not needed\"" >&6
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_gsl}"; then
 
@@ -8067,7 +8154,6 @@ echo "${ECHO_T}\"not needed\"" >&6
        VENDOR_INC_DIRS="${VENDOR_INC_DIRS} ${GSL_INC}"
 
    fi
-
 
 
 
@@ -8145,7 +8231,6 @@ echo "${ECHO_T}\"not needed\"" >&6
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${PCG_LIB}"
 
    fi
-
 
 
    # set up the libraries and include path
@@ -8230,7 +8315,6 @@ echo "${ECHO_T}\"not needed\"" >&6
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_blacs}" ; then
 
@@ -8265,7 +8349,6 @@ echo "${ECHO_T}\"not needed\"" >&6
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${BLACS_LIB}"
 
    fi
-
 
 
    # set up lapack libraries
@@ -8772,19 +8855,21 @@ echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
        fi
 
        # add vendors to rpath
-       for vendor_dir in ${VENDOR_LIB_DIRS};
-       do
-           if test "${dilem}" = "space"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "nospace"; then
-	       RPATH="${rptrigger}${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "colon"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           else
-               { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
+       for vendor_dir in ${VENDOR_LIB_DIRS}; do
+                      so_libs=`ls ${vendor_dir}/*.so 2>/dev/null`
+           if test ! "${so_libs:-none}" = "none"; then
+              if test "${dilem}" = "space"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "nospace"; then
+	          RPATH="${rptrigger}${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "colon"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              else
+                  { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
 echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
    { (exit 1); exit 1; }; }
-	   fi
+   	      fi
+           fi
        done
 
 
@@ -9080,7 +9165,6 @@ _ACEOF
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_gsl}"; then
 
@@ -9120,7 +9204,6 @@ _ACEOF
        VENDOR_INC_DIRS="${VENDOR_INC_DIRS} ${GSL_INC}"
 
    fi
-
 
 
 
@@ -9198,7 +9281,6 @@ _ACEOF
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${PCG_LIB}"
 
    fi
-
 
 
    # set up the libraries and include path
@@ -9283,7 +9365,6 @@ _ACEOF
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_blacs}" ; then
 
@@ -9318,7 +9399,6 @@ _ACEOF
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${BLACS_LIB}"
 
    fi
-
 
 
    # set up lapack libraries
@@ -9825,19 +9905,21 @@ echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
        fi
 
        # add vendors to rpath
-       for vendor_dir in ${VENDOR_LIB_DIRS};
-       do
-           if test "${dilem}" = "space"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "nospace"; then
-	       RPATH="${rptrigger}${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "colon"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           else
-               { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
+       for vendor_dir in ${VENDOR_LIB_DIRS}; do
+                      so_libs=`ls ${vendor_dir}/*.so 2>/dev/null`
+           if test ! "${so_libs:-none}" = "none"; then
+              if test "${dilem}" = "space"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "nospace"; then
+	          RPATH="${rptrigger}${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "colon"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              else
+                  { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
 echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
    { (exit 1); exit 1; }; }
-	   fi
+   	      fi
+           fi
        done
 
 
@@ -10048,7 +10130,6 @@ echo "$as_me: WARNING: \"xlC set to allow long long\"" >&2;}
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_gsl}"; then
 
@@ -10088,7 +10169,6 @@ echo "$as_me: WARNING: \"xlC set to allow long long\"" >&2;}
        VENDOR_INC_DIRS="${VENDOR_INC_DIRS} ${GSL_INC}"
 
    fi
-
 
 
 
@@ -10166,7 +10246,6 @@ echo "$as_me: WARNING: \"xlC set to allow long long\"" >&2;}
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${PCG_LIB}"
 
    fi
-
 
 
    # set up the libraries and include path
@@ -10251,7 +10330,6 @@ echo "$as_me: WARNING: \"xlC set to allow long long\"" >&2;}
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_blacs}" ; then
 
@@ -10286,7 +10364,6 @@ echo "$as_me: WARNING: \"xlC set to allow long long\"" >&2;}
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${BLACS_LIB}"
 
    fi
-
 
 
    # set up lapack libraries
@@ -10889,7 +10966,6 @@ echo "$as_me: error: \"We do not support vendor mpi on the SUN yet!\"" >&2;}
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_gsl}"; then
 
@@ -10929,7 +11005,6 @@ echo "$as_me: error: \"We do not support vendor mpi on the SUN yet!\"" >&2;}
        VENDOR_INC_DIRS="${VENDOR_INC_DIRS} ${GSL_INC}"
 
    fi
-
 
 
 
@@ -11007,7 +11082,6 @@ echo "$as_me: error: \"We do not support vendor mpi on the SUN yet!\"" >&2;}
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${PCG_LIB}"
 
    fi
-
 
 
    # set up the libraries and include path
@@ -11092,7 +11166,6 @@ echo "$as_me: error: \"We do not support vendor mpi on the SUN yet!\"" >&2;}
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_blacs}" ; then
 
@@ -11127,7 +11200,6 @@ echo "$as_me: error: \"We do not support vendor mpi on the SUN yet!\"" >&2;}
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${BLACS_LIB}"
 
    fi
-
 
 
    # set up lapack libraries
@@ -11634,19 +11706,21 @@ echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
        fi
 
        # add vendors to rpath
-       for vendor_dir in ${VENDOR_LIB_DIRS};
-       do
-           if test "${dilem}" = "space"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "nospace"; then
-	       RPATH="${rptrigger}${vendor_dir} ${RPATH}"
-           elif test "${dilem}" = "colon"; then
-	       RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
-           else
-               { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
+       for vendor_dir in ${VENDOR_LIB_DIRS}; do
+                      so_libs=`ls ${vendor_dir}/*.so 2>/dev/null`
+           if test ! "${so_libs:-none}" = "none"; then
+              if test "${dilem}" = "space"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "nospace"; then
+	          RPATH="${rptrigger}${vendor_dir} ${RPATH}"
+              elif test "${dilem}" = "colon"; then
+	          RPATH="${rptrigger} ${vendor_dir} ${RPATH}"
+              else
+                  { { echo "$as_me:$LINENO: error: \"Cannot determine what rpath format to use!\"" >&5
 echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
    { (exit 1); exit 1; }; }
-	   fi
+   	      fi
+           fi
        done
 
 
@@ -12004,7 +12078,6 @@ _ACEOF
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_gsl}"; then
 
@@ -12044,7 +12117,6 @@ _ACEOF
        VENDOR_INC_DIRS="${VENDOR_INC_DIRS} ${GSL_INC}"
 
    fi
-
 
 
 
@@ -12122,7 +12194,6 @@ _ACEOF
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${PCG_LIB}"
 
    fi
-
 
 
    # set up the libraries and include path
@@ -12207,7 +12278,6 @@ _ACEOF
    fi
 
 
-
    # set up the libraries and include path
    if test -n "${vendor_blacs}" ; then
 
@@ -12242,7 +12312,6 @@ _ACEOF
        VENDOR_LIB_DIRS="${VENDOR_LIB_DIRS} ${BLACS_LIB}"
 
    fi
-
 
 
    # set up lapack libraries
@@ -13655,6 +13724,8 @@ s,@BIBTEX@,$BIBTEX,;t t
 s,@BIBTEXFLAGS@,$BIBTEXFLAGS,;t t
 s,@XDVI@,$XDVI,;t t
 s,@XDVIFLAGS@,$XDVIFLAGS,;t t
+s,@PS2PDF@,$PS2PDF,;t t
+s,@DOTCMD@,$DOTCMD,;t t
 s,@DVIPS@,$DVIPS,;t t
 s,@DVIPSFLAGS@,$DVIPSFLAGS,;t t
 s,@LP@,$LP,;t t
