Preparation for release of draco-5_9_0.

diff --git a/src/rng/configure b/src/rng/configure
--- a/src/rng/configure
+++ b/src/rng/configure
@@ -846,7 +846,7 @@ Optional Packages:
   --with-c4=scalar,mpi,shmem
 		          turn on c4 (default scalar)
   --with-dbc=level      set Design-by-Contract
-  --with-cxx=gcc,sgi,kcc,compaq,guide
+  --with-cxx=gcc,icpc,sgi,kcc,compaq,guide
                           choose a c++ compiler (defaults are machine dependent)
   --with-opt=0,1,2,3    set optimization level (0 by default)
   --with-posix=num      give posix source (system-dependent defaults)
@@ -2470,8 +2470,6 @@ echo "$as_me: error: not found" >&2;}
    ;;
    Lahey)
 
-   # Check for working Lahey F90 compiler
-
    # Extract the first word of "lf95", so it can be a program name with args.
 set dummy lf95; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
@@ -2508,14 +2506,6 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
-   if test "${F90}" = lf95 && ${F90} --version 2>&1 | grep "Lahey"
-   then
-       :
-   else
-       { { echo "$as_me:$LINENO: error: not found" >&5
-echo "$as_me: error: not found" >&2;}
-   { (exit 1); exit 1; }; }
-   fi
 
    # F90FREE, F90FIXED AND MODFLAG
 
@@ -3575,8 +3565,6 @@ echo "$as_me: error: not found" >&2;}
        ;;
        i?86-pc-linux*)
 
-   # Check for working Lahey F90 compiler
-
    # Extract the first word of "lf95", so it can be a program name with args.
 set dummy lf95; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
@@ -3613,14 +3601,6 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
-   if test "${F90}" = lf95 && ${F90} --version 2>&1 | grep "Lahey"
-   then
-       :
-   else
-       { { echo "$as_me:$LINENO: error: not found" >&5
-echo "$as_me: error: not found" >&2;}
-   { (exit 1); exit 1; }; }
-   fi
 
    # F90FREE, F90FIXED AND MODFLAG
 
@@ -4752,9 +4732,9 @@ echo "$as_me: error: \"Did not find Compaq cxx compiler!\"" >&2;}
    { (exit 1); exit 1; }; }
        fi
 
-   elif test "${with_cxx}" = icc ; then
-       # Extract the first word of "icc", so it can be a program name with args.
-set dummy icc; ac_word=$2
+   elif test "${with_cxx}" = icpc ; then
+       # Extract the first word of "icpc", so it can be a program name with args.
+set dummy icpc; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_CXX+set}" = set; then
@@ -4770,7 +4750,7 @@ do
   test -z "$as_dir" && as_dir=.
   for ac_exec_ext in '' $ac_executable_extensions; do
   if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_prog_CXX="icc"
+    ac_cv_prog_CXX="icpc"
     echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
     break 2
   fi
@@ -4789,18 +4769,18 @@ echo "${ECHO_T}no" >&6
 fi
 
 
-       if test "${CXX}" = icc ; then
-	   CC='icc'
+       if test "${CXX}" = icpc ; then
+	   CC='icpc'
 
    echo "$as_me:$LINENO: checking \"configuration of ${CXX}/${CC} compilers\"" >&5
 echo $ECHO_N "checking \"configuration of ${CXX}/${CC} compilers\"... $ECHO_C" >&6
 
-   # icc SPECIFIC FLAGS
+   # icpc SPECIFIC FLAGS
 
    # LINKER AND LIBRARY
    LD='${CXX}'
 
-   # if shared then ar is icc
+   # if shared then ar is icpc
    if test "${enable_shared}" = yes ; then
        AR="${CXX}"
        ARFLAGS='-shared -o'
@@ -4825,9 +4805,9 @@ echo $ECHO_N "checking \"configuration of ${CXX}/${CC} compilers\"... $ECHO_C" >
 
        # turn off debug by default
        if test "${enable_debug:=no}" = yes ; then
-	   icc_opt_flags="-g -O${with_opt} -Ob1 -ip"
+	   icpc_opt_flags="-g -O${with_opt} -Ob1 -ip"
        else
-	   icc_opt_flags="-O${with_opt} -Ob1"
+	   icpc_opt_flags="-O${with_opt} -Ob1"
        fi
 
    #set up compiler when not optimized (turn off inlining with -Ob0)
@@ -4835,29 +4815,29 @@ echo $ECHO_N "checking \"configuration of ${CXX}/${CC} compilers\"... $ECHO_C" >
 
        # turn on debug by default
        if test "${enable_debug:=yes}" = yes ; then
-	   icc_opt_flags="-g -O0 -Ob0"
+	   icpc_opt_flags="-g -O0 -Ob0"
        else
-	   icc_opt_flags="-O0 -Ob0"
+	   icpc_opt_flags="-O0 -Ob0"
        fi
 
    fi
 
    # set the cxx and c flags
-   CXXFLAGS="${CXXFLAGS} ${icc_opt_flags}"
-   CFLAGS="${CFLAGS} ${icc_opt_flags}"
+   CXXFLAGS="${CXXFLAGS} ${icpc_opt_flags}"
+   CFLAGS="${CFLAGS} ${icpc_opt_flags}"
 
    # static linking option
    if test "${enable_static_ld}" = yes ; then
        LDFLAGS="${LDFLAGS} -static"
    fi
 
-   echo "$as_me:$LINENO: result: \"icc compiler flags set\"" >&5
-echo "${ECHO_T}\"icc compiler flags set\"" >&6
+   echo "$as_me:$LINENO: result: \"icpc compiler flags set\"" >&5
+echo "${ECHO_T}\"icpc compiler flags set\"" >&6
 
 
        else
-	   { { echo "$as_me:$LINENO: error: \"Did not find Intel icc compiler!\"" >&5
-echo "$as_me: error: \"Did not find Intel icc compiler!\"" >&2;}
+	   { { echo "$as_me:$LINENO: error: \"Did not find Intel icpc compiler!\"" >&5
+echo "$as_me: error: \"Did not find Intel icpc compiler!\"" >&2;}
    { (exit 1); exit 1; }; }
        fi
 
@@ -5866,7 +5846,7 @@ echo "${ECHO_T}\"--backend -lg2c added to LIBS\"" >&6
 	       LIBS="${LIBS} -lg2c"
 	       echo "$as_me:$LINENO: result: \"-lg2c added to LIBS\"" >&5
 echo "${ECHO_T}\"-lg2c added to LIBS\"" >&6
-	   elif test "${CXX}" = icc ; then
+	   elif test "${CXX}" = icpc ; then
                # Extract the first word of "g++", so it can be a program name with args.
 set dummy g++; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
@@ -5975,6 +5955,14 @@ echo "${ECHO_T}\"not needed\"" >&6
            echo "$as_me:$LINENO: result: \"not needed\"" >&5
 echo "${ECHO_T}\"not needed\"" >&6
        fi
+
+       #
+       # Set up fpe_trap for this platform.
+       #
+       cat >>confdefs.h <<\_ACEOF
+#define FPETRAP_LINUX_X86 1
+_ACEOF
+
 
        #
        # finalize vendors
@@ -6750,7 +6738,7 @@ echo "${ECHO_T}\"no vendor lib dirs defined\"" >&6
 	   # turn off ranlib
 	   RANLIB=':'
 
-	   # the g++/icc rpath needs Xlinker in front of it
+	   # the g++/icpc rpath needs Xlinker in front of it
            if test "${dilem}" = "space"; then
 	       RPATHA="-Xlinker -${rptrigger} \${curdir}"
 	       RPATHB="-Xlinker -${rptrigger} \${curdir}/.."
@@ -6785,7 +6773,7 @@ echo "$as_me: error: \"Cannot determine what rpath format to use!\"" >&2;}
 
        # add the intel math library for better performance when
        # compiling with intel
-       if test "${CXX}" = icc; then
+       if test "${CXX}" = icpc; then
 	   LIBS="$LIBS -limf"
        fi
 
@@ -7707,7 +7695,7 @@ echo "${ECHO_T}\"no vendor lib dirs defined\"" >&6
 	   # turn off ranlib
 	   RANLIB=':'
 
-	   # the g++/icc rpath needs Xlinker in front of it
+	   # the g++/icpc rpath needs Xlinker in front of it
            if test "${dilem}" = "space"; then
 	       RPATHA="-Xlinker -${rptrigger} \${curdir}"
 	       RPATHB="-Xlinker -${rptrigger} \${curdir}/.."
@@ -8717,7 +8705,7 @@ echo "${ECHO_T}\"no vendor lib dirs defined\"" >&6
 	   # turn off ranlib
 	   RANLIB=':'
 
-	   # the g++/icc rpath needs Xlinker in front of it
+	   # the g++/icpc rpath needs Xlinker in front of it
            if test "${dilem}" = "space"; then
 	       RPATHA="-Xlinker -${rptrigger} \${curdir}"
 	       RPATHB="-Xlinker -${rptrigger} \${curdir}/.."
@@ -8983,6 +8971,14 @@ echo "${ECHO_T}\"not needed\"" >&6
        #
        # end of libudm setup
        #
+
+       #
+       # Set up fpe_trap for this platform.
+       #
+       cat >>confdefs.h <<\_ACEOF
+#define FPETRAP_OSF_ALPHA 1
+_ACEOF
+
 
        #
        # finalize vendors
@@ -9758,7 +9754,7 @@ echo "${ECHO_T}\"no vendor lib dirs defined\"" >&6
 	   # turn off ranlib
 	   RANLIB=':'
 
-	   # the g++/icc rpath needs Xlinker in front of it
+	   # the g++/icpc rpath needs Xlinker in front of it
            if test "${dilem}" = "space"; then
 	       RPATHA="-Xlinker -${rptrigger} \${curdir}"
 	       RPATHB="-Xlinker -${rptrigger} \${curdir}/.."
@@ -11563,7 +11559,7 @@ echo "${ECHO_T}\"no vendor lib dirs defined\"" >&6
 	   # turn off ranlib
 	   RANLIB=':'
 
-	   # the g++/icc rpath needs Xlinker in front of it
+	   # the g++/icpc rpath needs Xlinker in front of it
            if test "${dilem}" = "space"; then
 	       RPATHA="-Xlinker -${rptrigger} \${curdir}"
 	       RPATHB="-Xlinker -${rptrigger} \${curdir}/.."
@@ -11801,7 +11797,7 @@ echo "${ECHO_T}\"--backend -lg2c added to LIBS\"" >&6
 	       LIBS="${LIBS} -lg2c"
 	       echo "$as_me:$LINENO: result: \"-lg2c added to LIBS\"" >&5
 echo "${ECHO_T}\"-lg2c added to LIBS\"" >&6
-	   elif test "${CXX}" = icc ; then
+	   elif test "${CXX}" = icpc ; then
                # Extract the first word of "g++", so it can be a program name with args.
 set dummy g++; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
@@ -11889,6 +11885,14 @@ echo "${ECHO_T}\"not needed\"" >&6
            echo "$as_me:$LINENO: result: \"not needed\"" >&5
 echo "${ECHO_T}\"not needed\"" >&6
        fi
+
+       #
+       # Set up fpe_trap for this platform.
+       #
+       cat >>confdefs.h <<\_ACEOF
+#define FPETRAP_DARWIN_PPC 1
+_ACEOF
+
 
        #
        # finalize vendors
